// PROMPT.md is the authored copy of the photo-to-faces.js prompt, and the face
// editor's "Copy prompt" button hands out the same text - so the app needs it
// as a module it can import, and that copy must never drift from the markdown.
//
// PROMPT.md stays the thing you edit. tools/pre-test.ts regenerates the module
// before every lint and test run, so a stale copy shows up as a diff rather
// than as a wrong prompt in someone's clipboard. To do it by hand:
//
//   node tools/faceFromPhoto/buildPrompt.ts

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SOURCE = join(import.meta.dirname, "PROMPT.md");
const OUT = join(
	import.meta.dirname,
	"../../src/common/faceFromPhotoPrompt.ts",
);

// Everything above the horizontal rule is instructions for the person running
// this (which chat models work, what to do about curly quotes); everything
// below it is what gets pasted to the model.
const promptBody = (markdown: string) => {
	const parts = markdown.split("\n---\n");
	if (parts.length !== 2) {
		throw new Error(
			`Expected exactly one "---" rule in PROMPT.md, found ${parts.length - 1}`,
		);
	}
	return parts[1]!.trim();
};

// Returns true if it actually wrote. Skipping an identical write keeps the
// file's mtime stable, so nothing downstream rebuilds for no reason.
export const buildFacePrompt = () => {
	const body = promptBody(readFileSync(SOURCE, "utf8"));
	const contents = `// GENERATED by tools/faceFromPhoto/buildPrompt.ts from
// tools/faceFromPhoto/PROMPT.md. Edit that file, not this one.
export const FACE_FROM_PHOTO_PROMPT = ${JSON.stringify(body)};
`;

	let existing;
	try {
		existing = readFileSync(OUT, "utf8");
	} catch {}

	if (existing === contents) {
		return false;
	}

	writeFileSync(OUT, contents);
	return true;
};

if (process.argv[1] === import.meta.filename) {
	console.log(
		buildFacePrompt() ? "faceFromPhotoPrompt.ts updated" : "no change",
	);
}
