import { assert, describe, test } from "vitest";
import {
	pregameLineupSynergy,
	pregameLineupSynergyFromPlayers,
	synergyForLineup,
	synergySkillCounts,
	type SynergyCompositeRating,
} from "./synergy.ts";

// THESE NUMBERS CAME OUT OF THE SIM, not out of this file.
//
// The synergy maths lived inside GameSim.basketball and was moved out so the
// front office could use it. A refactor of a formula the whole game sim rests
// on has to be proved, not asserted, so these expectations were generated by
// running the ORIGINAL inline code over eight lineups - six pseudo-random, two
// at the extremes - and pasted in. If a future edit changes what a lineup is
// worth, these fail, which is the point: the front office and the sim must
// grade a roster identically or a team optimises for something game night does
// not reward.
const CASES: {
	players: SynergyCompositeRating[];
	synergy: { off: number; def: number; reb: number };
}[] = [
	{
		players: [
			{
				shootingThreePointer: 0.655,
				athleticism: 0.305,
				dribbling: 0.632,
				defenseInterior: 0.996,
				defensePerimeter: 0.679,
				shootingLowPost: 0.673,
				passing: 0.173,
				rebounding: 0.883,
			},
			{
				shootingThreePointer: 0.707,
				athleticism: 0.828,
				dribbling: 0.739,
				defenseInterior: 0.338,
				defensePerimeter: 0.794,
				shootingLowPost: 0.192,
				passing: 0.58,
				rebounding: 0.234,
			},
			{
				shootingThreePointer: 0.209,
				athleticism: 0.788,
				dribbling: 0.871,
				defenseInterior: 0.844,
				defensePerimeter: 0.111,
				shootingLowPost: 0.47,
				passing: 0.731,
				rebounding: 0.366,
			},
			{
				shootingThreePointer: 0.279,
				athleticism: 0.368,
				dribbling: 0.919,
				defenseInterior: 0.871,
				defensePerimeter: 0.419,
				shootingLowPost: 0.429,
				passing: 0.82,
				rebounding: 0.173,
			},
			{
				shootingThreePointer: 0.158,
				athleticism: 0.318,
				dribbling: 0.377,
				defenseInterior: 0.504,
				defensePerimeter: 0.973,
				shootingLowPost: 0.468,
				passing: 0.754,
				rebounding: 0.225,
			},
		],
		synergy: {
			off: 0.6777229498838209,
			def: 0.5634626241358942,
			reb: 0.25174356094544476,
		},
	},
	{
		players: [
			{
				shootingThreePointer: 0.436,
				athleticism: 0.873,
				dribbling: 0.819,
				defenseInterior: 0.308,
				defensePerimeter: 0.536,
				shootingLowPost: 0.847,
				passing: 0.7,
				rebounding: 0.111,
			},
			{
				shootingThreePointer: 0.589,
				athleticism: 0.092,
				dribbling: 0.691,
				defenseInterior: 0.4,
				defensePerimeter: 0.7,
				shootingLowPost: 0.254,
				passing: 0.382,
				rebounding: 0.4,
			},
			{
				shootingThreePointer: 0.418,
				athleticism: 0.944,
				dribbling: 0.431,
				defenseInterior: 0.023,
				defensePerimeter: 0.252,
				shootingLowPost: 0.133,
				passing: 0.667,
				rebounding: 0.005,
			},
			{
				shootingThreePointer: 0.286,
				athleticism: 0.281,
				dribbling: 0.418,
				defenseInterior: 0.218,
				defensePerimeter: 0.803,
				shootingLowPost: 0.479,
				passing: 0.538,
				rebounding: 0.848,
			},
			{
				shootingThreePointer: 0.613,
				athleticism: 0.699,
				dribbling: 0.021,
				defenseInterior: 0.554,
				defensePerimeter: 0.449,
				shootingLowPost: 0.511,
				passing: 0.664,
				rebounding: 0.292,
			},
		],
		synergy: {
			off: 0.5114955726562901,
			def: 0.3522899324022053,
			reb: 0.2523115343054151,
		},
	},
	{
		players: [
			{
				shootingThreePointer: 0.488,
				athleticism: 0.954,
				dribbling: 0.202,
				defenseInterior: 0.519,
				defensePerimeter: 0.906,
				shootingLowPost: 0.61,
				passing: 0.014,
				rebounding: 0.64,
			},
			{
				shootingThreePointer: 0.649,
				athleticism: 0.399,
				dribbling: 0.805,
				defenseInterior: 0.686,
				defensePerimeter: 0.283,
				shootingLowPost: 0.793,
				passing: 0.995,
				rebounding: 0.493,
			},
			{
				shootingThreePointer: 0.19,
				athleticism: 0.569,
				dribbling: 0.673,
				defenseInterior: 0.862,
				defensePerimeter: 0.572,
				shootingLowPost: 0.693,
				passing: 0.086,
				rebounding: 0.934,
			},
			{
				shootingThreePointer: 0.087,
				athleticism: 0.243,
				dribbling: 0.453,
				defenseInterior: 0.804,
				defensePerimeter: 0.31,
				shootingLowPost: 0.861,
				passing: 0.235,
				rebounding: 0.805,
			},
			{
				shootingThreePointer: 0.409,
				athleticism: 0.43,
				dribbling: 0.009,
				defenseInterior: 0.323,
				defensePerimeter: 0.708,
				shootingLowPost: 0.826,
				passing: 0.794,
				rebounding: 0.997,
			},
		],
		synergy: {
			off: 0.3898880643655791,
			def: 0.5065106588530045,
			reb: 0.49998516482358235,
		},
	},
	{
		players: [
			{
				shootingThreePointer: 0.592,
				athleticism: 0.86,
				dribbling: 0.307,
				defenseInterior: 0.006,
				defensePerimeter: 0.254,
				shootingLowPost: 0.528,
				passing: 0.647,
				rebounding: 0.686,
			},
			{
				shootingThreePointer: 0.672,
				athleticism: 0.488,
				dribbling: 0.656,
				defenseInterior: 0.918,
				defensePerimeter: 0.682,
				shootingLowPost: 0.13,
				passing: 0.57,
				rebounding: 0.213,
			},
			{
				shootingThreePointer: 0.676,
				athleticism: 0.442,
				dribbling: 0.321,
				defenseInterior: 0.685,
				defensePerimeter: 0.356,
				shootingLowPost: 0.376,
				passing: 0.246,
				rebounding: 0.331,
			},
			{
				shootingThreePointer: 0.119,
				athleticism: 0.543,
				dribbling: 0.97,
				defenseInterior: 0.701,
				defensePerimeter: 0.518,
				shootingLowPost: 0.826,
				passing: 0.8,
				rebounding: 0.32,
			},
			{
				shootingThreePointer: 0.478,
				athleticism: 0.479,
				dribbling: 0.136,
				defenseInterior: 0.887,
				defensePerimeter: 0.345,
				shootingLowPost: 0.008,
				passing: 0.609,
				rebounding: 0.39,
			},
		],
		synergy: {
			off: 0.6079803864464358,
			def: 0.5052509522260242,
			reb: 0.19014350346321746,
		},
	},
	{
		players: [
			{
				shootingThreePointer: 0.097,
				athleticism: 0.131,
				dribbling: 0.122,
				defenseInterior: 0.124,
				defensePerimeter: 0.77,
				shootingLowPost: 0.71,
				passing: 0.703,
				rebounding: 0.354,
			},
			{
				shootingThreePointer: 0.219,
				athleticism: 0.471,
				dribbling: 0.925,
				defenseInterior: 0.314,
				defensePerimeter: 0.095,
				shootingLowPost: 0.886,
				passing: 0.356,
				rebounding: 0.983,
			},
			{
				shootingThreePointer: 0.225,
				athleticism: 0.25,
				dribbling: 0.582,
				defenseInterior: 0.974,
				defensePerimeter: 0.254,
				shootingLowPost: 0.732,
				passing: 0.305,
				rebounding: 0.819,
			},
			{
				shootingThreePointer: 0.287,
				athleticism: 0.524,
				dribbling: 0.727,
				defenseInterior: 0.526,
				defensePerimeter: 0.695,
				shootingLowPost: 0.684,
				passing: 0.272,
				rebounding: 0.136,
			},
			{
				shootingThreePointer: 0.769,
				athleticism: 0.031,
				dribbling: 0.13,
				defenseInterior: 0.494,
				defensePerimeter: 0.463,
				shootingLowPost: 0.365,
				passing: 0.698,
				rebounding: 0.627,
			},
		],
		synergy: {
			off: 0.3906998360456219,
			def: 0.500026551548459,
			reb: 0.49527437004523944,
		},
	},
	{
		players: [
			{
				shootingThreePointer: 0.577,
				athleticism: 0.346,
				dribbling: 0.434,
				defenseInterior: 0.434,
				defensePerimeter: 0.59,
				shootingLowPost: 0.313,
				passing: 0.933,
				rebounding: 0.931,
			},
			{
				shootingThreePointer: 0.615,
				athleticism: 0.402,
				dribbling: 0.885,
				defenseInterior: 0.27,
				defensePerimeter: 0.043,
				shootingLowPost: 0.403,
				passing: 0.399,
				rebounding: 0.937,
			},
			{
				shootingThreePointer: 0.976,
				athleticism: 0.032,
				dribbling: 0.416,
				defenseInterior: 0.378,
				defensePerimeter: 0.172,
				shootingLowPost: 0.898,
				passing: 0.295,
				rebounding: 0.954,
			},
			{
				shootingThreePointer: 0.718,
				athleticism: 0.991,
				dribbling: 0.784,
				defenseInterior: 0.467,
				defensePerimeter: 0.669,
				shootingLowPost: 0.895,
				passing: 0.307,
				rebounding: 0.783,
			},
			{
				shootingThreePointer: 0.598,
				athleticism: 0.626,
				dribbling: 0.56,
				defenseInterior: 0.085,
				defensePerimeter: 0.91,
				shootingLowPost: 0.745,
				passing: 0.025,
				rebounding: 0.656,
			},
		],
		synergy: {
			off: 0.6965744916912018,
			def: 0.18186245238456258,
			reb: 0.4999998169114169,
		},
	},
	{
		players: [
			{
				shootingThreePointer: 0,
				athleticism: 0,
				dribbling: 0,
				defenseInterior: 0,
				defensePerimeter: 0,
				shootingLowPost: 0,
				passing: 0,
				rebounding: 0,
			},
			{
				shootingThreePointer: 0,
				athleticism: 0,
				dribbling: 0,
				defenseInterior: 0,
				defensePerimeter: 0,
				shootingLowPost: 0,
				passing: 0,
				rebounding: 0,
			},
			{
				shootingThreePointer: 0,
				athleticism: 0,
				dribbling: 0,
				defenseInterior: 0,
				defensePerimeter: 0,
				shootingLowPost: 0,
				passing: 0,
				rebounding: 0,
			},
			{
				shootingThreePointer: 0,
				athleticism: 0,
				dribbling: 0,
				defenseInterior: 0,
				defensePerimeter: 0,
				shootingLowPost: 0,
				passing: 0,
				rebounding: 0,
			},
			{
				shootingThreePointer: 0,
				athleticism: 0,
				dribbling: 0,
				defenseInterior: 0,
				defensePerimeter: 0,
				shootingLowPost: 0,
				passing: 0,
				rebounding: 0,
			},
		],
		synergy: {
			off: 0.000376611047608976,
			def: 1.4180128613458345e-5,
			reb: 4.299213601140033e-5,
		},
	},
	{
		players: [
			{
				shootingThreePointer: 1,
				athleticism: 1,
				dribbling: 1,
				defenseInterior: 1,
				defensePerimeter: 1,
				shootingLowPost: 1,
				passing: 1,
				rebounding: 1,
			},
			{
				shootingThreePointer: 1,
				athleticism: 1,
				dribbling: 1,
				defenseInterior: 1,
				defensePerimeter: 1,
				shootingLowPost: 1,
				passing: 1,
				rebounding: 1,
			},
			{
				shootingThreePointer: 1,
				athleticism: 1,
				dribbling: 1,
				defenseInterior: 1,
				defensePerimeter: 1,
				shootingLowPost: 1,
				passing: 1,
				rebounding: 1,
			},
			{
				shootingThreePointer: 1,
				athleticism: 1,
				dribbling: 1,
				defenseInterior: 1,
				defensePerimeter: 1,
				shootingLowPost: 1,
				passing: 1,
				rebounding: 1,
			},
			{
				shootingThreePointer: 1,
				athleticism: 1,
				dribbling: 1,
				defenseInterior: 1,
				defensePerimeter: 1,
				shootingLowPost: 1,
				passing: 1,
				rebounding: 1,
			},
		],
		synergy: {
			off: 0.9999608321530457,
			def: 0.8333041873954818,
			reb: 0.4999999764585638,
		},
	},
];

describe("synergy matches the game sim it was extracted from", () => {
	for (const [i, c] of CASES.entries()) {
		test(`lineup ${i}`, () => {
			const actual = synergyForLineup(
				c.players.map((compositeRating) => ({ compositeRating })),
			);
			assert.closeTo(actual.off, c.synergy.off, 1e-12);
			assert.closeTo(actual.def, c.synergy.def, 1e-12);
			assert.closeTo(actual.reb, c.synergy.reb, 1e-12);
		});
	}
});

describe("the shape of the three numbers", () => {
	const flat = (v: number): SynergyCompositeRating => ({
		shootingThreePointer: v,
		athleticism: v,
		dribbling: v,
		defenseInterior: v,
		defensePerimeter: v,
		shootingLowPost: v,
		passing: v,
		rebounding: v,
	});
	const lineup = (v: number) =>
		Array.from({ length: 5 }, () => ({ compositeRating: flat(v) }));

	// The ranges the front office scales against. They are NOT all 0..1 - def
	// tops out at 5/6 and reb at 1/2 - and a fit weight that assumed otherwise
	// would silently value rebounding at half what it thought.
	test("each number has its own ceiling", () => {
		const best = synergyForLineup(lineup(1));
		assert.closeTo(best.off, 1, 0.001);
		assert.closeTo(best.def, 5 / 6, 0.001);
		assert.closeTo(best.reb, 1 / 2, 0.001);
	});

	test("a lineup with no skills at all scores nothing", () => {
		const worst = synergyForLineup(lineup(0));
		assert.isBelow(worst.off, 0.01);
		assert.isBelow(worst.def, 0.01);
		assert.isBelow(worst.reb, 0.01);
	});

	// The whole reason this matters to a front office: five copies of the same
	// good player are worth less than five good players who do different things.
	test("five identical shooters are worth less than a balanced five", () => {
		const shooter: SynergyCompositeRating = {
			...flat(0.3),
			shootingThreePointer: 0.9,
			dribbling: 0.9,
			passing: 0.9,
		};
		const rim: SynergyCompositeRating = {
			...flat(0.3),
			defenseInterior: 0.9,
			rebounding: 0.9,
			shootingLowPost: 0.9,
			athleticism: 0.9,
		};
		const wing: SynergyCompositeRating = {
			...flat(0.3),
			shootingThreePointer: 0.9,
			defensePerimeter: 0.9,
			athleticism: 0.9,
		};

		const allShooters = synergyForLineup(
			Array.from({ length: 5 }, () => ({ compositeRating: shooter })),
		);
		const balanced = synergyForLineup(
			[shooter, shooter, wing, rim, rim].map((compositeRating) => ({
				compositeRating,
			})),
		);

		const total = (s: { off: number; def: number; reb: number }) =>
			s.off + s.def + s.reb;
		assert.isAbove(total(balanced), total(allShooters));
	});
});

describe("synergySkillCounts", () => {
	test("counts fractionally, so a near-miss is not nothing", () => {
		// Just under the 0.59 three-point cutoff.
		const counts = synergySkillCounts([
			{
				compositeRating: {
					shootingThreePointer: 0.58,
					athleticism: 0,
					dribbling: 0,
					defenseInterior: 0,
					defensePerimeter: 0,
					shootingLowPost: 0,
					passing: 0,
					rebounding: 0,
				},
			},
		]);
		assert.isAbove(counts["3"], 0.3);
		assert.isBelow(counts["3"], 0.5);
	});
});

// The pregame readings the point spread prices from. See getGameSpread.ts for
// the coefficient they feed; what matters here is WHICH players get read.
describe("pregameLineupSynergy", () => {
	const flat = (v: number): SynergyCompositeRating => ({
		shootingThreePointer: v,
		athleticism: v,
		dribbling: v,
		defenseInterior: v,
		defensePerimeter: v,
		shootingLowPost: v,
		passing: v,
		rebounding: v,
	});
	const man = (v: number, injured = false) => ({
		injured,
		compositeRating: flat(v),
	});

	test("fewer than five available men is no reading at all", () => {
		assert.strictEqual(
			pregameLineupSynergy([man(0.6), man(0.6), man(0.6), man(0.6)]),
			undefined,
		);
	});

	test("an injured man does not count toward the five", () => {
		const four = [man(0.6), man(0.6), man(0.6), man(0.6)];
		assert.strictEqual(
			pregameLineupSynergy([...four, man(0.6, true)]),
			undefined,
		);
		assert.notStrictEqual(pregameLineupSynergy([...four, man(0.6)]), undefined);
	});

	test("five to nine men reads the first five alone", () => {
		const starters = [man(0.8), man(0.8), man(0.8), man(0.8), man(0.8)];
		const withBench = [...starters, man(0.1), man(0.1)];
		assert.strictEqual(
			pregameLineupSynergy(withBench),
			pregameLineupSynergy(starters),
		);
	});

	test("ten men blends the second five in at 30%", () => {
		const good = Array.from({ length: 5 }, () => man(0.8));
		const bad = Array.from({ length: 5 }, () => man(0.1));
		const blended = pregameLineupSynergy([...good, ...bad])!;
		const firstOnly = pregameLineupSynergy(good)!;
		const secondOnly = pregameLineupSynergy(bad)!;
		assert.closeTo(blended, 0.7 * firstOnly + 0.3 * secondOnly, 1e-9);
	});

	test("an injured starter promotes the next man into the five", () => {
		const roster = [
			man(0.8, true),
			...Array.from({ length: 5 }, () => man(0.5)),
		];
		// The reading equals a healthy five of 0.5s - the injured 0.8 never plays.
		assert.strictEqual(
			pregameLineupSynergy(roster),
			pregameLineupSynergy(Array.from({ length: 5 }, () => man(0.5))),
		);
	});
});

describe("pregameLineupSynergyFromPlayers", () => {
	// A raw player row: a full ratings line at one level, so the eight synergy
	// composites come out deterministic.
	const rawMan = (
		level: number,
		{
			value = 50,
			gamesRemaining = 0,
		}: { value?: number; gamesRemaining?: number } = {},
	) => {
		const ratings: any = { season: 2026, pos: "F" };
		for (const key of [
			"hgt",
			"stre",
			"spd",
			"jmp",
			"endu",
			"ins",
			"dnk",
			"ft",
			"fg",
			"tp",
			"oiq",
			"diq",
			"drb",
			"pss",
			"reb",
		]) {
			ratings[key] = level;
		}
		return { injury: { gamesRemaining }, ratings: [ratings], value };
	};
	const opts = {
		numDaysInFuture: 0,
		playThroughInjuries: [0, 0] as [number, number],
		playoffs: false,
	};

	test("mirrors team.ovr's availability window", () => {
		const healthy = Array.from({ length: 5 }, () => rawMan(60));
		// Out one game today; available for a game three days out.
		const outToday = rawMan(60, { gamesRemaining: 1 });
		assert.strictEqual(
			pregameLineupSynergyFromPlayers([...healthy.slice(1), outToday], opts),
			undefined,
		);
		assert.notStrictEqual(
			pregameLineupSynergyFromPlayers([...healthy.slice(1), outToday], {
				...opts,
				numDaysInFuture: 3,
			}),
			undefined,
		);
	});

	test("orders by value, so the reading is the likely rotation's", () => {
		const stars = Array.from({ length: 5 }, () => rawMan(80, { value: 90 }));
		const bench = Array.from({ length: 5 }, () => rawMan(20, { value: 10 }));
		// Shuffled input, same reading: ordering comes from value, not position in
		// the array.
		const a = pregameLineupSynergyFromPlayers([...stars, ...bench], opts);
		const b = pregameLineupSynergyFromPlayers(
			[bench[0]!, ...stars, ...bench.slice(1)],
			opts,
		);
		assert.strictEqual(a, b);
	});

	test("a man playing through injury is damped, not dropped", () => {
		const healthy = Array.from({ length: 5 }, () => rawMan(60));
		const hurt = rawMan(60, { gamesRemaining: 2 });
		const withPlayThrough = pregameLineupSynergyFromPlayers(
			[...healthy.slice(1), hurt],
			{ ...opts, playThroughInjuries: [3, 3] },
		);
		const fullyHealthy = pregameLineupSynergyFromPlayers(healthy, opts);
		assert.notStrictEqual(withPlayThrough, undefined);
		assert.ok(withPlayThrough! <= fullyHealthy!);
	});
});
