// THE PLAYBOOK: real NBA sets, written down role by role, for the 2.5D
// court to run on its way to whatever shot the sim says came next.
//
// Built from public breakdowns of the sets teams actually run (pick-and-roll
// families, Horns, Floppy, Chicago, Hammer, Spain, Princeton, Triangle,
// inbound plays, transition), with usage weighted toward how often each shows
// up in today's game (NBA.com Synergy play types, 2024-25).
//
// Notation, so a set reads the way a coach would draw it:
//
//   Spots are feet from the attacked rim: x across (+ is the offense's right),
//   y out toward half court. Every set is drawn to one side; the court may
//   mirror it.
//
//   start    the five spots, role 1 to 5; * marks who has the ball
//   needs    what each role asks of the man in it, role 1 to 5
//   steps    one beat each, its actions in the order they happen:
//              5 screen 1 top ball      5 screens for 1, planted at the top
//              1 dribble R_elbow attack
//              5 move rim roll
//              1 pass 2 chest
//              5 handoff 2 get          5 hands it off to 2
//              4 post L_block seal
//   options  how the set scores: shooter, zone, shot, spot, the beat after
//            which it is open, who passes it (- for nobody) and how, the
//            Synergy play type and a weight; after a |, the extra moves of
//            that read
//   risks    where it goes wrong: beat, who, and how

export const SPOTS: Record<string, readonly [number, number]> = {
	top: [0, 25.5],
	L_slot: [-13, 22],
	R_slot: [13, 22],
	L_wing: [-21.8, 13.2],
	R_wing: [21.8, 13.2],
	L_corner: [-23.9, -2],
	R_corner: [23.9, -2],
	L_elbow: [-8, 13.75],
	R_elbow: [8, 13.75],
	high_post: [0, 13.75],
	L_block: [-9, 2.5],
	R_block: [9, 2.5],
	L_short_corner: [-15, 0],
	R_short_corner: [15, 0],
	L_dunker: [-8, -2.5],
	R_dunker: [8, -2.5],
	L_mid_wing: [-13.5, 8],
	R_mid_wing: [13.5, 8],
	L_lane: [-4, 7],
	R_lane: [4, 7],
	rim: [0, 0],
	L_hash: [-15, 31],
	R_hash: [15, 31],
	backcourt_mid: [0, 45],
	inbound_baseline_L: [-6, -6.75],
	inbound_baseline_R: [6, -6.75],
	inbound_sideline_L: [-26, 22.75],
	inbound_sideline_R: [26, 22.75],
	own_rim: [0, 83.5],
	own_L_outlet: [-19, 70],
	own_R_outlet: [19, 70],
	backcourt_L: [-17, 50],
	backcourt_R: [17, 50],
	inbound_own_baseline: [-6, 90],
};

export type PlaySource = {
	id: string;
	cat: "half" | "early" | "break" | "blob" | "slob" | "late";
	// How often it is run, 1 (a specialty) to 10 (every few trips).
	use: number;
	start: string;
	needs: string;
	steps: string[];
	options: string[];
	risks: string[];
};

export const PLAYBOOK: PlaySource[] = [
	{
		id: "high-pnr-spread",
		cat: "half",
		use: 10,
		start: "top* R_corner L_corner L_wing R_elbow",
		needs:
			"ballHandler | shooter spacer | shooter spacer | spacer stretchBig | screener rollMan lobThreat",
		steps: [
			"5 screen 1 top ball",
			"1 dribble R_elbow attack; 5 move rim roll; 4 move L_slot lift",
		],
		options: [
			"5 rim dunk rim 1 1 lob PRRollMan 3",
			"1 mid pull_up R_elbow 1 - - PRBallHandler 3",
			"1 three pull_up top 0 - - PRBallHandler 2",
			"1 rim layup rim 1 - - PRBallHandler 2 | 5 move L_dunker seal; 1 dribble rim attack",
			"1 mid floater R_lane 1 - - PRBallHandler 2 | 1 dribble R_lane attack",
			"2 three catch_and_shoot R_corner 1 1 kickout Spotup 2",
			"3 three catch_and_shoot L_corner 1 1 skip Spotup 2",
			"4 three catch_and_shoot L_slot 1 1 skip Spotup 1",
			"5 post hook R_lane 0 1 bounce PRRollMan 1 | 1 dribble R_slot attack; 5 move R_lane roll",
			"5 post hook R_block 1 1 entry Postup 1 | 5 post R_block seal",
		],
		risks: ["0 5 screen", "1 1 lost"],
	},
	{
		id: "high-pnr-short-roll",
		cat: "half",
		use: 7,
		start: "top* R_corner L_corner L_dunker R_elbow",
		needs:
			"ballHandler | shooter spacer | shooter spacer | big rimRunner | screener rollMan passer",
		steps: [
			"5 screen 1 top ball",
			"1 dribble R_slot retreat; 5 move high_post short_roll",
			"1 pass 5 pocket",
		],
		options: [
			"5 mid catch_and_shoot high_post 2 1 - PRRollMan 2",
			"5 mid floater R_lane 2 - - PRRollMan 2 | 5 dribble R_lane attack",
			"4 rim dunk L_dunker 2 5 dump_off Cut 3",
			"3 three catch_and_shoot L_corner 2 5 kickout Spotup 2",
			"2 three catch_and_shoot R_corner 2 5 kickout Spotup 1",
		],
		risks: ["0 5 screen", "2 1 pass"],
	},
	{
		id: "pick-and-pop",
		cat: "half",
		use: 7,
		start: "top* R_corner L_wing R_elbow L_dunker",
		needs:
			"ballHandler | shooter | shooter spacer | screener popBig stretchBig | big rimRunner",
		steps: [
			"4 screen 1 top ball",
			"1 dribble L_elbow attack; 4 move R_slot pop",
		],
		options: [
			"4 three catch_and_shoot R_slot 1 1 skip PRRollMan 4",
			"1 mid pull_up L_elbow 1 - - PRBallHandler 2",
			"5 rim dunk L_dunker 1 1 dump_off Cut 2",
			"3 three catch_and_shoot L_wing 1 1 kickout Spotup 1",
			"4 mid pull_up R_elbow 1 - - PRRollMan 1 | 1 pass 4 skip; 4 dribble R_elbow attack",
		],
		risks: ["0 4 screen", "1 1 lost"],
	},
	{
		id: "side-pnr",
		cat: "half",
		use: 8,
		start: "R_wing* R_corner L_corner L_slot R_elbow",
		needs: "ballHandler | shooter | shooter | spacer | screener rollMan",
		steps: [
			"5 screen 1 R_wing ball",
			"1 dribble high_post drive_middle; 5 move rim roll; 4 move top lift",
		],
		options: [
			"5 rim dunk rim 1 1 pocket PRRollMan 3",
			"1 mid pull_up high_post 1 - - PRBallHandler 3",
			"1 mid floater R_lane 1 - - PRBallHandler 2 | 1 dribble R_lane attack",
			"2 three catch_and_shoot R_corner 1 1 kickout Spotup 2",
			"3 three catch_and_shoot L_corner 1 1 skip Spotup 2",
			"4 three catch_and_shoot top 1 1 kickout Spotup 1",
			"5 post hook R_lane 0 1 bounce PRRollMan 1 | 1 dribble high_post drive_middle; 5 move R_lane roll",
		],
		risks: ["0 5 screen", "1 1 lost", "1 1 charge"],
	},
	{
		id: "side-pnr-empty-corner",
		cat: "half",
		use: 6,
		start: "R_wing* L_corner L_wing top R_elbow",
		needs:
			"ballHandler | shooter | shooter | spacer | screener rollMan lobThreat",
		steps: [
			"5 screen 1 R_wing ball",
			"1 dribble R_elbow attack; 5 move rim roll",
		],
		options: [
			"5 rim alley_oop rim 1 1 lob PRRollMan 4",
			"1 mid pull_up R_elbow 1 - - PRBallHandler 2",
			"1 rim layup rim 1 - - PRBallHandler 2 | 5 move L_dunker seal; 1 dribble rim attack",
			"2 three catch_and_shoot L_corner 1 1 skip Spotup 2",
			"4 three catch_and_shoot top 1 1 kickout Spotup 1",
		],
		risks: ["0 5 screen", "1 1 lost"],
	},
	{
		id: "side-pnr-shake",
		cat: "half",
		use: 6,
		start: "L_wing* L_corner R_corner R_slot L_elbow",
		needs:
			"ballHandler | shooter | shooter | shooter spacer | screener rollMan",
		steps: [
			"5 screen 1 L_wing ball",
			"1 dribble high_post drive_middle; 5 move rim roll; 2 move L_wing lift; 4 move R_wing drift",
		],
		options: [
			"2 three catch_and_shoot L_wing 1 1 kickout Spotup 3",
			"5 rim dunk rim 1 1 pocket PRRollMan 2",
			"1 mid pull_up high_post 1 - - PRBallHandler 2",
			"3 three catch_and_shoot R_corner 1 1 skip Spotup 1",
			"4 three catch_and_shoot R_wing 1 1 kickout Spotup 1",
		],
		risks: ["0 5 screen", "1 1 lost", "1 1 charge"],
	},
	{
		id: "slot-pnr",
		cat: "half",
		use: 7,
		start: "R_slot* R_corner L_corner L_wing R_elbow",
		needs: "ballHandler | shooter | shooter | spacer | screener rollMan",
		steps: [
			"5 screen 1 R_slot ball",
			"1 dribble L_lane drive_middle; 5 move rim roll; 4 move L_slot lift",
		],
		options: [
			"1 mid floater L_lane 1 - - PRBallHandler 3",
			"1 rim layup rim 1 - - PRBallHandler 2 | 5 move R_dunker seal; 1 dribble rim attack",
			"5 rim dunk rim 1 1 pocket PRRollMan 2",
			"3 three catch_and_shoot L_corner 1 1 kickout Spotup 2",
			"2 three catch_and_shoot R_corner 1 1 skip Spotup 1",
			"4 three catch_and_shoot L_slot 1 1 kickout Spotup 1",
			"5 post floater R_lane 0 1 bounce PRRollMan 1 | 1 dribble high_post drive_middle; 5 move R_lane roll",
		],
		risks: ["0 5 screen", "1 1 lost", "1 1 charge"],
	},
	{
		id: "step-up-screen",
		cat: "early",
		use: 6,
		start: "R_wing* R_corner L_corner L_slot R_block",
		needs:
			"ballHandler | shooter | shooter | spacer stretchBig | rimRunner screener rollMan",
		steps: [
			"5 screen 1 R_wing step_up",
			"1 dribble high_post drive_middle; 5 move rim roll; 4 move top lift",
		],
		options: [
			"5 rim dunk rim 1 1 pocket PRRollMan 3",
			"1 mid pull_up high_post 1 - - PRBallHandler 2",
			"1 rim layup rim 1 - - PRBallHandler 2 | 5 move L_dunker seal; 1 dribble rim attack",
			"2 three catch_and_shoot R_corner 1 1 kickout Spotup 2",
			"4 three catch_and_shoot top 1 1 kickout Spotup 1",
		],
		risks: ["0 5 screen", "1 1 lost", "1 1 charge"],
	},
	{
		id: "drag-screen",
		cat: "early",
		use: 7,
		start: "L_hash* R_corner L_corner R_dunker backcourt_mid",
		needs: "ballHandler | shooter | shooter | rimRunner big | screener rollMan",
		steps: [
			"1 dribble L_slot advance; 5 move top sprint",
			"5 screen 1 L_slot drag",
			"1 dribble high_post drive_middle; 5 move rim roll",
		],
		options: [
			"1 three pull_up L_slot 1 - - PRBallHandler 3",
			"5 rim dunk rim 2 1 pocket PRRollMan 2",
			"1 mid pull_up high_post 2 - - PRBallHandler 2",
			"4 rim dunk R_dunker 2 1 dump_off Cut 1",
			"2 three catch_and_shoot R_corner 2 1 kickout Transition 1",
			"3 three catch_and_shoot L_corner 2 1 kickout Transition 1",
			"5 post hook L_lane 1 1 bounce PRRollMan 1 | 1 dribble high_post drive_middle; 5 move L_lane roll",
		],
		risks: ["1 5 screen", "2 1 lost", "2 1 charge"],
	},
	{
		id: "double-drag",
		cat: "early",
		use: 6,
		start: "L_hash* R_corner L_corner top backcourt_mid",
		needs:
			"ballHandler | shooter | shooter | screener popBig stretchBig | screener rollMan lobThreat",
		steps: [
			"4 screen 1 L_slot double_drag; 5 move top sprint",
			"1 dribble top attack; 4 move L_wing pop; 5 screen 1 top double_drag",
			"1 dribble R_elbow attack; 5 move rim roll",
		],
		options: [
			"5 rim alley_oop rim 2 1 lob PRRollMan 3",
			"4 three catch_and_shoot L_wing 2 1 skip PRRollMan 3",
			"1 mid pull_up R_elbow 2 - - PRBallHandler 2",
			"2 three catch_and_shoot R_corner 2 1 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 2 1 skip Spotup 1",
		],
		risks: ["0 4 screen", "1 1 lost", "1 5 screen", "2 1 lost"],
	},
	{
		id: "spain-pnr",
		cat: "half",
		use: 5,
		start: "top* high_post L_corner R_corner L_elbow",
		needs:
			"ballHandler | shooter screener | shooter | shooter | screener rollMan lobThreat",
		steps: [
			"5 screen 1 top ball",
			"1 dribble R_slot attack; 5 move R_lane roll; 2 screen 5 high_post spain",
			"5 move rim roll; 2 move top pop; 1 dribble R_elbow attack",
		],
		options: [
			"5 rim alley_oop rim 2 1 lob PRRollMan 3",
			"2 three catch_and_shoot top 2 1 kickout Spotup 3",
			"1 mid pull_up R_elbow 2 - - PRBallHandler 2",
			"4 three catch_and_shoot R_corner 2 1 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 2 1 skip Spotup 1",
		],
		risks: ["0 5 screen", "1 1 lost", "2 1 lost"],
	},
	{
		id: "snake-pnr",
		cat: "half",
		use: 6,
		start: "L_slot* R_corner L_corner R_wing L_elbow",
		needs:
			"ballHandler | shooter | shooter | spacer | screener rollMan lobThreat",
		steps: [
			"5 screen 1 L_slot ball",
			"1 dribble high_post attack; 5 move rim roll",
			"1 dribble L_elbow snake",
		],
		options: [
			"1 mid pull_up L_elbow 2 - - PRBallHandler 4",
			"1 mid floater L_lane 2 - - PRBallHandler 2 | 1 dribble L_lane attack",
			"5 rim alley_oop rim 2 1 lob PRRollMan 2",
			"3 three catch_and_shoot L_corner 2 1 kickout Spotup 1",
			"4 three catch_and_shoot R_wing 2 1 skip Spotup 1",
		],
		risks: ["0 5 screen", "1 1 lost", "1 1 charge", "2 1 lost"],
	},
	{
		id: "ram-pnr",
		cat: "half",
		use: 5,
		start: "top* L_corner R_elbow L_wing R_dunker",
		needs:
			"ballHandler | shooter | screener shooter | spacer | screener rollMan",
		steps: [
			"3 screen 5 R_block down; 5 move R_elbow sprint",
			"5 screen 1 top ball; 3 move R_corner clear_out",
			"1 dribble R_elbow attack; 5 move rim roll",
		],
		options: [
			"5 rim dunk rim 2 1 pocket PRRollMan 3",
			"1 mid pull_up R_elbow 2 - - PRBallHandler 2",
			"1 three pull_up top 1 - - PRBallHandler 1",
			"3 three catch_and_shoot R_corner 2 1 kickout Spotup 2",
			"2 three catch_and_shoot L_corner 2 1 skip Spotup 1",
			"4 three catch_and_shoot L_wing 2 1 kickout Spotup 1",
		],
		risks: ["0 3 screen", "1 5 screen", "2 1 lost"],
	},
	{
		id: "ghost-screen-pnr",
		cat: "half",
		use: 5,
		start: "L_slot* L_corner R_corner R_wing R_dunker",
		needs: "ballHandler | shooter screener | shooter | spacer | big rimRunner",
		steps: [
			"2 screen 1 L_slot ghost",
			"2 move L_wing pop; 1 dribble top attack",
		],
		options: [
			"2 three catch_and_shoot L_wing 1 1 kickout Spotup 4",
			"2 rim layup rim 0 1 bounce Cut 1 | 2 move rim slip",
			"1 three pull_up top 1 - - PRBallHandler 1",
			"1 rim layup rim 1 - - PRBallHandler 1 | 1 dribble rim drive_middle",
			"5 rim dunk R_dunker 1 1 dump_off Cut 1",
			"3 three catch_and_shoot R_corner 1 1 skip Spotup 1",
		],
		risks: ["1 1 lost"],
	},
	{
		id: "pnr-slip",
		cat: "half",
		use: 4,
		start: "top* R_corner L_corner L_wing R_elbow",
		needs:
			"ballHandler | shooter | shooter | spacer | screener rollMan lobThreat",
		steps: [
			"5 screen 1 top ball",
			"5 move rim slip; 1 dribble R_slot hesitation",
		],
		options: [
			"5 rim dunk rim 1 1 bounce PRRollMan 4",
			"2 three catch_and_shoot R_corner 1 1 kickout Spotup 2",
			"4 three catch_and_shoot L_wing 1 1 skip Spotup 1",
			"1 three pull_up R_slot 1 - - PRBallHandler 1",
		],
		risks: ["0 5 screen"],
	},
	{
		id: "guard-guard-pnr",
		cat: "half",
		use: 6,
		start: "top* R_wing L_corner R_corner L_dunker",
		needs:
			"ballHandler | screener shooter | shooter | shooter spacer | big rimRunner",
		steps: [
			"2 screen 1 top ball",
			"1 dribble L_slot attack; 2 move R_slot pop",
		],
		options: [
			"2 three catch_and_shoot R_slot 1 1 skip PRRollMan 3",
			"1 three pull_up L_slot 1 - - PRBallHandler 2",
			"1 rim layup rim 1 - - PRBallHandler 2 | 1 dribble rim drive_middle",
			"2 rim layup rim 0 1 bounce PRRollMan 1 | 2 move rim slip",
			"5 rim dunk L_dunker 1 1 dump_off Cut 1",
			"3 three catch_and_shoot L_corner 1 1 kickout Spotup 1",
		],
		risks: ["0 2 screen", "1 1 lost"],
	},
	{
		id: "inverted-pnr",
		cat: "half",
		use: 4,
		start: "R_slot R_corner L_corner L_wing top*",
		needs:
			"screener shooter | shooter | shooter | spacer | ballHandler big passer",
		steps: [
			"1 screen 5 top ball",
			"5 dribble L_elbow attack; 1 move R_slot pop",
		],
		options: [
			"1 three catch_and_shoot R_slot 1 5 skip PRRollMan 3",
			"5 post hook L_lane 1 - - PRBallHandler 2 | 5 dribble L_lane attack",
			"5 rim dunk rim 1 - - PRBallHandler 1 | 5 dribble rim attack",
			"1 rim layup rim 0 5 bounce Cut 1 | 1 move rim slip",
			"3 three catch_and_shoot L_corner 1 5 kickout Spotup 1",
			"4 three catch_and_shoot L_wing 1 5 kickout Spotup 1",
		],
		risks: ["0 1 screen", "1 5 lost"],
	},
	{
		id: "veer-stagger",
		cat: "half",
		use: 3,
		start: "R_wing* L_corner R_corner L_elbow R_block",
		needs:
			"ballHandler | shooter offBallShooter | shooter | screener | screener big",
		steps: [
			"5 screen 1 R_wing step_up",
			"1 dribble top drive_middle; 5 move L_short_corner sprint; 4 move L_mid_wing jog",
			"5+4 screen 2 L_short_corner+L_mid_wing stagger; 2 move L_wing sprint",
		],
		options: [
			"2 three catch_and_shoot L_wing 2 1 chest OffScreen 4",
			"4 rim layup rim 2 1 lob Cut 1 | 4 move rim slip",
			"5 post hook L_block 2 1 entry Postup 1 | 5 post L_block seal",
			"1 mid pull_up high_post 2 - - PRBallHandler 1 | 1 dribble high_post attack",
			"3 three catch_and_shoot R_corner 2 1 kickout Spotup 1",
		],
		risks: ["0 5 screen", "1 1 lost", "2 5 screen"],
	},
	{
		id: "pnr-reject-ice",
		cat: "half",
		use: 5,
		start: "R_wing* R_corner L_slot L_corner R_elbow",
		needs: "ballHandler | shooter | shooter | shooter | screener rollMan",
		steps: [
			"5 screen 1 R_wing ball",
			"1 dribble R_short_corner reject; 2 move R_wing lift; 5 move R_lane roll; 3 move L_wing drift",
		],
		options: [
			"1 mid pull_up R_short_corner 1 - - PRBallHandler 2",
			"1 rim layup rim 1 - - PRBallHandler 2 | 1 dribble rim drive_baseline",
			"2 three catch_and_shoot R_wing 1 1 kickout Spotup 2",
			"5 rim dunk rim 1 1 dump_off PRRollMan 2 | 5 move rim roll",
			"4 three catch_and_shoot L_corner 1 1 skip Spotup 1",
		],
		risks: ["0 5 screen", "1 1 lost", "1 1 charge"],
	},
	{
		id: "stack-pnr",
		cat: "half",
		use: 4,
		start: "L_slot* high_post L_corner R_corner top",
		needs:
			"ballHandler | shooter offBallShooter | shooter | shooter | screener rollMan",
		steps: [
			"5 screen 1 top ball",
			"1 dribble R_elbow attack; 2 move L_slot pop; 5 move rim roll",
		],
		options: [
			"2 three catch_and_shoot L_slot 1 1 kickout Spotup 3",
			"5 rim alley_oop rim 1 1 lob PRRollMan 2",
			"1 mid pull_up R_elbow 1 - - PRBallHandler 2",
			"4 three catch_and_shoot R_corner 1 1 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 1 1 skip Spotup 1",
		],
		risks: ["0 5 screen", "1 1 lost"],
	},
	{
		id: "pnr-re-screen",
		cat: "half",
		use: 5,
		start: "top* R_corner L_corner R_wing L_elbow",
		needs: "ballHandler | shooter | shooter | spacer | screener rollMan",
		steps: [
			"5 screen 1 top ball",
			"1 dribble R_slot attack",
			"1 dribble top retreat; 5 screen 1 top ball",
			"1 dribble L_elbow attack; 5 move rim roll",
		],
		options: [
			"5 rim dunk rim 3 1 pocket PRRollMan 3",
			"1 mid pull_up L_elbow 3 - - PRBallHandler 3",
			"3 three catch_and_shoot L_corner 3 1 kickout Spotup 1",
			"2 three catch_and_shoot R_corner 3 1 skip Spotup 1",
			"4 three catch_and_shoot R_wing 3 1 skip Spotup 1",
		],
		risks: ["0 5 screen", "1 1 lost", "2 5 screen", "3 1 lost"],
	},
	{
		id: "horns-pnr",
		cat: "half",
		use: 8,
		start: "top* R_corner L_corner L_elbow R_elbow",
		needs:
			"ballHandler | shooter spacer | shooter spacer | popBig stretchBig | screener rollMan",
		steps: [
			"5 screen 1 top ball",
			"1 dribble R_elbow attack; 5 move rim roll; 4 move L_slot pop",
		],
		options: [
			"5 rim dunk rim 1 1 pocket PRRollMan 3",
			"4 three catch_and_shoot L_slot 1 1 skip Spotup 2",
			"1 mid pull_up R_elbow 1 - - PRBallHandler 2",
			"1 three pull_up top 0 - - PRBallHandler 1",
			"2 three catch_and_shoot R_corner 1 1 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 1 1 skip Spotup 1",
			"5 post hook R_lane 0 1 bounce PRRollMan 1 | 1 dribble R_elbow attack; 5 move R_lane roll",
		],
		risks: ["0 5 screen", "1 1 lost"],
	},
	{
		id: "horns-flare",
		cat: "half",
		use: 5,
		start: "top* R_corner L_corner L_elbow R_elbow",
		needs:
			"ballHandler | shooter | shooter | screener popBig stretchBig | screener rollMan",
		steps: [
			"4 screen 1 top ball",
			"1 dribble L_elbow attack; 5 screen 4 high_post flare; 4 move R_wing flare",
			"5 move rim roll",
		],
		options: [
			"4 three catch_and_shoot R_wing 2 1 skip OffScreen 4",
			"5 rim alley_oop rim 2 1 lob Cut 2",
			"1 mid pull_up L_elbow 2 - - PRBallHandler 2",
			"3 three catch_and_shoot L_corner 2 1 kickout Spotup 1",
			"2 three catch_and_shoot R_corner 2 1 skip Spotup 1",
		],
		risks: ["0 4 screen", "1 1 lost", "1 5 screen"],
	},
	{
		id: "horns-twist",
		cat: "half",
		use: 5,
		start: "top* R_corner L_corner L_elbow R_elbow",
		needs:
			"ballHandler | shooter | shooter | screener popBig | screener rollMan",
		steps: [
			"4 screen 1 top ball",
			"1 dribble L_slot attack; 4 move L_wing pop",
			"5 screen 1 L_slot ball",
			"1 dribble R_elbow crossover; 5 move rim roll",
		],
		options: [
			"5 rim dunk rim 3 1 pocket PRRollMan 3",
			"1 mid pull_up R_elbow 3 - - PRBallHandler 3",
			"4 three catch_and_shoot L_wing 3 1 skip Spotup 2",
			"2 three catch_and_shoot R_corner 3 1 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 3 1 skip Spotup 1",
		],
		risks: ["0 4 screen", "1 1 lost", "2 5 screen", "3 1 lost"],
	},
	{
		id: "horns-elbow-get",
		cat: "half",
		use: 5,
		start: "top* R_corner L_corner L_elbow R_elbow",
		needs:
			"ballHandler shooter | shooter ballHandler | shooter | big rimRunner | handoffBig passer",
		steps: [
			"1 pass 5 chest; 2 move R_wing v_cut",
			"1 move L_slot relocate",
			"5 dribble R_slot advance; 5 handoff 2 get",
			"2 dribble R_elbow attack; 5 move rim roll; 4 move L_dunker roll",
		],
		options: [
			"2 three pull_up R_slot 2 5 - Handoff 3",
			"2 mid pull_up R_elbow 3 - - Handoff 2",
			"5 rim dunk rim 3 2 pocket Cut 2",
			"4 rim dunk L_dunker 3 2 dump_off Cut 1",
			"1 three catch_and_shoot L_slot 3 2 skip Spotup 1",
			"3 three catch_and_shoot L_corner 3 2 skip Spotup 1",
		],
		risks: ["0 1 pass", "2 2 lost", "3 2 lost"],
	},
	{
		id: "horns-punch",
		cat: "half",
		use: 4,
		start: "top* R_corner L_corner L_elbow R_elbow",
		needs:
			"ballHandler passer | shooter | shooter | stretchBig passer | postScorer big",
		steps: [
			"1 dribble R_wing advance; 2 move L_wing clear_out",
			"5 post R_block seal; 4 move top lift",
			"1 pass 5 entry",
			"5 post R_block back_down",
		],
		options: [
			"5 post hook R_block 2 1 - Postup 1",
			"5 post hook R_block 3 - - Postup 3",
			"5 post fadeaway R_block 3 - - Postup 2",
			"5 rim dunk rim 3 - - Postup 1 | 5 post rim drop_step",
			"1 three catch_and_shoot R_wing 3 5 kickout Spotup 2",
			"4 three catch_and_shoot top 3 5 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 3 5 skip Spotup 1",
		],
		risks: ["2 1 pass", "3 5 lost", "3 5 travel"],
	},
	{
		id: "horns-through",
		cat: "half",
		use: 4,
		start: "top* R_corner L_corner L_elbow R_elbow",
		needs:
			"ballHandler shooter | shooter | shooter ballHandler | handoffBig passer | popBig",
		steps: [
			"1 pass 4 chest",
			"3 move L_wing v_cut; 1 move L_corner clear_out",
			"4 dribble L_slot advance; 4 handoff 3 get",
			"3 dribble high_post attack; 4 move rim roll; 5 move R_slot pop",
		],
		options: [
			"3 three pull_up L_slot 2 4 - Handoff 3",
			"3 mid pull_up high_post 3 - - Handoff 2",
			"4 rim dunk rim 3 3 pocket Cut 2",
			"5 three catch_and_shoot R_slot 3 3 skip Spotup 1",
			"1 three catch_and_shoot L_corner 3 3 kickout Spotup 1",
			"2 three catch_and_shoot R_corner 3 3 skip Spotup 1",
		],
		risks: ["0 1 pass", "2 3 lost", "3 3 lost", "3 3 charge"],
	},
	{
		id: "horns-ucla",
		cat: "half",
		use: 3,
		start: "top* R_corner L_corner L_elbow R_elbow",
		needs:
			"cutter ballHandler | shooter passer | shooter | spacer | screener stretchBig",
		steps: [
			"2 move R_wing v_cut",
			"1 pass 2 chest",
			"5 screen 1 R_elbow rip; 1 move rim rip_cut",
			"1 move R_block seal; 5 move top pop",
		],
		options: [
			"1 rim layup rim 2 2 lob Cut 3",
			"5 three catch_and_shoot top 3 2 swing Spotup 2",
			"1 post fadeaway R_block 3 2 entry Postup 2",
			"3 three catch_and_shoot L_corner 3 2 skip Spotup 1",
		],
		risks: ["1 1 pass"],
	},
	{
		id: "horns-out",
		cat: "half",
		use: 4,
		start: "top* R_corner L_corner L_elbow R_elbow",
		needs:
			"ballHandler shooter | shooter ballHandler | shooter | screener big | screener rollMan",
		steps: [
			"4 screen 3 L_block down; 5 screen 2 R_block down; 3 move L_wing v_cut; 2 move R_wing v_cut",
			"1 pass 2 chest",
			"5 screen 2 R_wing step_up; 1 move L_slot relocate; 4 move L_dunker seal",
			"2 dribble R_elbow attack; 5 move rim roll",
		],
		options: [
			"2 three catch_and_shoot R_wing 1 1 - OffScreen 3",
			"2 mid pull_up R_elbow 3 - - PRBallHandler 2",
			"5 rim dunk rim 3 2 pocket PRRollMan 2",
			"4 rim dunk L_dunker 3 2 dump_off Cut 1",
			"3 three catch_and_shoot L_wing 3 2 skip Spotup 1",
			"1 three catch_and_shoot L_slot 3 2 kickout Spotup 1",
		],
		risks: ["0 4 screen", "0 5 screen", "1 1 pass", "2 5 screen", "3 2 lost"],
	},
	{
		id: "horns-dive",
		cat: "half",
		use: 4,
		start: "top* R_corner L_corner L_elbow R_elbow",
		needs:
			"ballHandler | shooter | shooter | rimRunner lobThreat | screener popBig",
		steps: [
			"4 move L_dunker roll; 5 screen 1 top ball",
			"1 dribble R_elbow attack; 5 move R_slot pop",
		],
		options: [
			"4 rim dunk L_dunker 1 1 lob Cut 3",
			"5 three catch_and_shoot R_slot 1 1 kickout PRRollMan 2",
			"1 mid pull_up R_elbow 1 - - PRBallHandler 2",
			"1 mid floater R_lane 1 - - PRBallHandler 1 | 1 dribble R_lane attack",
			"2 three catch_and_shoot R_corner 1 1 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 1 1 skip Spotup 1",
		],
		risks: ["0 5 screen", "1 1 lost"],
	},
	{
		id: "horns-stagger",
		cat: "half",
		use: 3,
		start: "top* R_corner L_corner L_elbow R_elbow",
		needs:
			"ballHandler | shooter offBallShooter | passer shooter | screener | screener big",
		steps: [
			"3 move L_wing v_cut",
			"1 pass 3 chest; 1 move L_corner clear_out",
			"5+4 screen 2 R_block+high_post stagger; 2 move top sprint",
		],
		options: [
			"2 three catch_and_shoot top 2 3 swing OffScreen 4",
			"2 mid floater R_lane 2 3 bounce OffScreen 1 | 2 move R_lane curl",
			"4 rim layup rim 2 3 lob Cut 1 | 4 move rim slip",
			"1 three catch_and_shoot L_corner 2 3 kickout Spotup 1",
		],
		risks: ["1 1 pass", "2 5 screen"],
	},
	{
		id: "horns-double",
		cat: "half",
		use: 3,
		start: "top* R_corner L_corner L_elbow R_elbow",
		needs:
			"ballHandler | shooter | shooter | screener popBig | screener rollMan",
		steps: [
			"5+4 screen 1 top+L_slot stagger",
			"1 dribble L_elbow attack; 5 move rim roll; 4 move L_wing pop",
		],
		options: [
			"5 rim alley_oop rim 1 1 lob PRRollMan 3",
			"4 three catch_and_shoot L_wing 1 1 kickout PRRollMan 2",
			"1 mid pull_up L_elbow 1 - - PRBallHandler 2",
			"3 three catch_and_shoot L_corner 1 1 kickout Spotup 1",
			"2 three catch_and_shoot R_corner 1 1 skip Spotup 1",
		],
		risks: ["0 5 screen", "1 1 lost"],
	},
	{
		id: "floppy",
		cat: "half",
		use: 4,
		start: "top* rim L_block R_block R_short_corner",
		needs:
			"ballHandler passer | shooter offBallShooter | screener wing | screener big postScorer | screener big",
		steps: [
			"3 screen 2 L_block down; 4+5 screen 2 R_block+R_short_corner stagger double",
			"2 move R_wing sprint",
			"1 pass 2 chest; 4 post R_block seal; 5 move R_corner pop; 3 move L_wing pop",
		],
		options: [
			"2 three catch_and_shoot R_wing 1 1 chest OffScreen 4",
			"2 three catch_and_shoot L_wing 0 1 chest OffScreen 2 | 2 move L_wing sprint",
			"2 mid catch_and_shoot R_elbow 0 1 chest OffScreen 1 | 2 move R_elbow curl",
			"2 three catch_and_shoot R_corner 0 1 skip OffScreen 1 | 5 move R_wing pop; 2 move R_corner fade",
			"4 post hook R_block 2 2 entry Postup 1",
			"2 mid pull_up R_mid_wing 2 - - OffScreen 1 | 2 dribble R_mid_wing attack",
		],
		risks: ["0 3 screen", "0 4 screen", "2 1 pass"],
	},
	{
		id: "floppy-into-pnr",
		cat: "half",
		use: 3,
		start: "top* rim L_block R_block R_short_corner",
		needs:
			"passer | shooter ballHandler | screener shooter | screener big | screener rollMan",
		steps: [
			"3 screen 2 L_block down; 4+5 screen 2 R_block+R_short_corner stagger double",
			"2 move R_wing sprint",
			"1 pass 2 chest; 3 move L_corner pop; 4 move L_dunker jog; 1 move L_slot relocate",
			"5 screen 2 R_wing step_up",
			"2 dribble high_post drive_middle; 5 move rim roll",
		],
		options: [
			"2 three catch_and_shoot R_wing 1 1 chest OffScreen 2",
			"2 mid pull_up high_post 4 - - PRBallHandler 3",
			"5 rim dunk rim 4 2 pocket PRRollMan 2",
			"4 rim dunk L_dunker 4 2 dump_off Cut 1",
			"3 three catch_and_shoot L_corner 4 2 skip Spotup 1",
			"1 three catch_and_shoot L_slot 4 2 kickout Spotup 1",
		],
		risks: [
			"0 3 screen",
			"0 4 screen",
			"2 1 pass",
			"3 5 screen",
			"4 2 lost",
			"4 2 charge",
		],
	},
	{
		id: "chicago",
		cat: "half",
		use: 7,
		start: "top* R_corner L_corner R_block R_elbow",
		needs:
			"ballHandler shooter | shooter ballHandler | shooter | screener | handoffBig rollMan",
		steps: [
			"5 move R_slot lift; 1 pass 5 chest",
			"4 screen 2 R_block pin_down; 2 move R_wing v_cut; 1 move L_wing relocate",
			"5 handoff 2 get",
			"2 dribble R_elbow attack; 5 move rim roll; 4 move R_corner pop",
		],
		options: [
			"2 three pull_up R_slot 2 5 - Handoff 4",
			"2 mid pull_up R_elbow 3 - - Handoff 2",
			"2 rim layup rim 3 - - Handoff 2 | 5 move L_dunker seal; 2 dribble rim attack",
			"5 rim dunk rim 3 2 pocket Cut 2",
			"4 three catch_and_shoot R_corner 3 2 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 3 2 skip Spotup 1",
			"1 three catch_and_shoot L_wing 3 2 skip Spotup 1",
			"5 post hook R_lane 2 2 bounce Cut 1 | 2 dribble R_elbow attack; 5 move R_lane roll",
		],
		risks: ["0 1 pass", "1 4 screen", "2 2 lost", "3 2 lost"],
	},
	{
		id: "chicago-backdoor",
		cat: "half",
		use: 3,
		start: "top* R_corner L_corner R_block R_elbow",
		needs:
			"ballHandler | cutter shooter | shooter | screener shooter | handoffBig passer",
		steps: [
			"5 move R_slot lift; 1 pass 5 chest",
			"4 screen 2 R_block pin_down; 2 move R_wing v_cut; 1 move L_wing relocate",
			"5 handoff 2 fake",
			"2 move rim backdoor; 4 move R_corner pop",
		],
		options: [
			"2 rim layup rim 3 5 bounce Cut 4",
			"5 rim dunk rim 2 - - Misc 1 | 5 dribble rim attack",
			"4 three catch_and_shoot R_corner 3 5 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 3 5 skip Spotup 1",
		],
		risks: ["0 1 pass", "1 4 screen", "2 2 lost"],
	},
	{
		id: "elbow-chicago",
		cat: "half",
		use: 3,
		start: "top* L_corner R_wing L_block R_elbow",
		needs:
			"ballHandler | shooter ballHandler | shooter | screener | handoffBig passer rollMan",
		steps: [
			"1 pass 5 chest",
			"1 move R_corner clear_out; 4 screen 2 L_block pin_down; 2 move L_wing v_cut",
			"5 dribble top advance; 5 handoff 2 get",
			"2 dribble high_post attack; 5 move rim roll; 4 move L_corner pop",
		],
		options: [
			"2 three pull_up top 2 5 - Handoff 3",
			"2 mid pull_up high_post 3 - - Handoff 2",
			"5 rim dunk rim 3 2 pocket Cut 2",
			"4 three catch_and_shoot L_corner 3 2 kickout Spotup 1",
			"1 three catch_and_shoot R_corner 3 2 kickout Spotup 1",
			"3 three catch_and_shoot R_wing 3 2 kickout Spotup 1",
		],
		risks: ["0 1 pass", "1 4 screen", "2 2 lost", "3 2 lost", "3 2 charge"],
	},
	{
		id: "hammer",
		cat: "half",
		use: 4,
		start: "top* R_wing L_wing R_elbow L_block",
		needs:
			"ballHandler shooter | slasher ballHandler passer | shooter offBallShooter | screener rollMan | screener big",
		steps: [
			"1 pass 2 chest",
			"4 screen 2 R_wing ball; 1 move L_slot relocate",
			"2 dribble R_short_corner drive_baseline; 4 move R_lane roll; 5 screen 3 L_mid_wing hammer; 3 move L_corner drift",
			"2 dribble R_dunker drive_baseline",
		],
		options: [
			"3 three catch_and_shoot L_corner 3 2 skip Spotup 4",
			"2 rim layup R_dunker 3 - - PRBallHandler 2",
			"2 mid pull_up R_short_corner 2 - - PRBallHandler 1",
			"4 rim dunk rim 3 2 dump_off PRRollMan 1 | 4 move rim roll",
			"5 rim dunk L_dunker 3 2 lob Cut 1 | 5 move L_dunker roll",
			"1 three catch_and_shoot L_slot 3 2 kickout Spotup 1",
		],
		risks: [
			"0 1 pass",
			"1 4 screen",
			"2 2 lost",
			"2 2 charge",
			"3 2 lost",
			"3 2 charge",
		],
	},
	{
		id: "zipper-pnr",
		cat: "half",
		use: 4,
		start: "L_slot* R_block L_corner R_corner R_lane",
		needs:
			"passer shooter | ballHandler shooter | shooter | shooter | screener rollMan",
		steps: [
			"5 screen 2 R_lane zipper; 2 move R_slot sprint",
			"1 pass 2 chest; 1 move L_wing relocate",
			"5 screen 2 R_slot ball",
			"2 dribble high_post drive_middle; 5 move rim roll",
		],
		options: [
			"2 three catch_and_shoot R_slot 1 1 - OffScreen 2",
			"2 mid pull_up high_post 3 - - PRBallHandler 3",
			"5 rim dunk rim 3 2 pocket PRRollMan 2",
			"4 three catch_and_shoot R_corner 3 2 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 3 2 skip Spotup 1",
			"1 three catch_and_shoot L_wing 3 2 kickout Spotup 1",
		],
		risks: ["1 1 pass", "2 5 screen", "3 2 lost", "3 2 charge"],
	},
	{
		id: "zipper-post",
		cat: "half",
		use: 2,
		start: "L_slot* R_block L_corner R_corner R_lane",
		needs: "passer | passer shooter | shooter | shooter | screener postScorer",
		steps: [
			"5 screen 2 R_lane zipper; 2 move R_slot sprint",
			"1 pass 2 chest; 5 post R_block seal",
			"2 pass 5 entry; 2 move R_wing relocate",
			"5 post R_block back_down",
		],
		options: [
			"5 post hook R_block 2 2 - Postup 2",
			"5 post fadeaway R_block 3 - - Postup 2",
			"5 rim layup rim 3 - - Postup 1 | 5 post rim drop_step",
			"2 three catch_and_shoot R_wing 3 5 kickout Spotup 2",
			"4 three catch_and_shoot R_corner 3 5 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 3 5 skip Spotup 1",
		],
		risks: ["1 1 pass", "2 2 pass", "3 5 lost", "3 5 travel"],
	},
	{
		id: "elbow-face-up-iso",
		cat: "half",
		use: 3,
		start: "top* R_corner L_corner R_block L_dunker",
		needs: "passer | shooter | shooter | isoScorer postScorer | big rimRunner",
		steps: [
			"4 move R_elbow flash",
			"1 pass 4 chest; 1 move L_wing relocate",
			"4 post R_elbow face_up",
		],
		options: [
			"4 mid fadeaway R_elbow 2 - - Isolation 3",
			"4 mid pull_up R_elbow 2 - - Isolation 2",
			"4 rim layup rim 2 - - Isolation 1 | 4 dribble rim drive_baseline",
			"5 rim dunk L_dunker 2 4 dump_off Cut 1 | 4 dribble R_lane attack",
			"2 three catch_and_shoot R_corner 2 4 kickout Spotup 1",
			"1 three catch_and_shoot L_wing 2 4 skip Spotup 1",
		],
		risks: ["1 1 pass", "2 4 lost", "2 4 travel"],
	},
	{
		id: "elbow-split",
		cat: "half",
		use: 3,
		start: "top* R_corner L_wing L_corner R_elbow",
		needs:
			"screener cutter | shooter offBallShooter | shooter | shooter | passer big",
		steps: [
			"1 pass 5 chest",
			"1 screen 2 R_mid_wing down; 2 move R_wing v_cut",
			"1 move R_corner pop",
		],
		options: [
			"2 three catch_and_shoot R_wing 1 5 chest OffScreen 3",
			"1 rim layup rim 1 5 bounce Cut 2 | 1 move rim slip",
			"1 three catch_and_shoot R_corner 2 5 kickout Spotup 1",
			"5 mid pull_up R_elbow 2 - - Isolation 1",
			"3 three catch_and_shoot L_wing 2 5 skip Spotup 1",
		],
		risks: ["0 1 pass", "1 1 screen"],
	},
	{
		id: "elbow-handback-flare",
		cat: "half",
		use: 3,
		start: "R_slot* L_slot R_corner L_elbow R_elbow",
		needs:
			"ballHandler | shooter offBallShooter | shooter | screener | handoffBig rollMan",
		steps: [
			"1 pass 5 chest",
			"5 handoff 1 get",
			"1 dribble high_post attack; 5 move rim roll; 4 screen 2 L_slot flare; 2 move L_wing flare",
		],
		options: [
			"2 three catch_and_shoot L_wing 2 1 skip OffScreen 3",
			"1 mid pull_up high_post 2 - - Handoff 2",
			"5 rim dunk rim 2 1 pocket Cut 2",
			"4 rim layup rim 2 1 lob Cut 1 | 5 move R_dunker seal; 4 move rim slip",
			"3 three catch_and_shoot R_corner 2 1 kickout Spotup 1",
		],
		risks: ["0 1 pass", "1 1 lost", "2 1 lost", "2 1 charge", "2 4 screen"],
	},
	{
		id: "pinch-post",
		cat: "half",
		use: 3,
		start: "top* R_wing L_wing R_corner L_elbow",
		needs:
			"ballHandler cutter | shooter | shooter | shooter | handoffBig passer",
		steps: [
			"1 pass 5 chest",
			"5 handoff 1 get; 3 move L_corner clear_out",
			"1 dribble L_lane attack; 5 move rim roll",
		],
		options: [
			"1 mid pull_up L_elbow 1 5 - Handoff 2",
			"1 mid floater L_lane 2 - - Handoff 2",
			"5 rim dunk rim 2 1 dump_off Cut 2",
			"1 rim layup rim 0 5 bounce Cut 1 | 5 handoff 1 fake; 1 move rim curl",
			"3 three catch_and_shoot L_corner 2 1 kickout Spotup 1",
			"2 three catch_and_shoot R_wing 2 1 skip Spotup 1",
		],
		risks: ["0 1 pass", "1 1 lost", "2 1 lost", "2 1 charge"],
	},
	{
		id: "pistol-dho",
		cat: "early",
		use: 5,
		start: "R_hash* R_wing L_corner L_wing backcourt_mid",
		needs:
			"ballHandler shooter | ballHandler shooter | shooter | shooter spacer | screener rollMan",
		steps: [
			"1 dribble R_slot advance; 5 move top jog",
			"1 handoff 2 get; 1 move R_corner clear_out",
			"5 screen 2 R_slot ball",
			"2 dribble high_post drive_middle; 5 move rim roll",
		],
		options: [
			"2 three pull_up R_slot 1 1 - Handoff 2",
			"2 mid pull_up high_post 3 - - PRBallHandler 3",
			"5 rim dunk rim 3 2 pocket PRRollMan 2",
			"1 three catch_and_shoot R_corner 3 2 kickout Spotup 1",
			"4 three catch_and_shoot L_wing 3 2 skip Spotup 1",
			"3 three catch_and_shoot L_corner 3 2 skip Spotup 1",
		],
		risks: ["1 2 lost", "2 5 screen", "3 2 lost", "3 2 charge"],
	},
	{
		id: "pistol-keep",
		cat: "early",
		use: 3,
		start: "R_hash* R_wing L_corner L_wing L_dunker",
		needs: "ballHandler | screener shooter | shooter | shooter | rimRunner big",
		steps: [
			"1 dribble R_slot advance",
			"1 handoff 2 fake; 2 screen 1 R_slot ball",
			"1 dribble high_post drive_middle; 2 move R_wing pop",
		],
		options: [
			"1 mid pull_up high_post 2 - - PRBallHandler 2",
			"1 rim layup rim 2 - - PRBallHandler 2 | 1 dribble rim drive_middle",
			"2 three catch_and_shoot R_wing 2 1 kickout PRRollMan 2",
			"2 rim layup rim 1 1 bounce Cut 1 | 2 move rim slip",
			"5 rim dunk L_dunker 2 1 dump_off Cut 1",
			"3 three catch_and_shoot L_corner 2 1 skip Spotup 1",
		],
		risks: ["1 2 lost", "1 2 screen", "2 1 lost", "2 1 charge"],
	},
	{
		id: "pistol-flare",
		cat: "early",
		use: 2,
		start: "R_hash* R_wing L_corner L_wing backcourt_mid",
		needs:
			"shooter ballHandler | ballHandler | shooter | shooter | screener rollMan",
		steps: [
			"1 dribble R_slot advance; 5 move top jog",
			"1 handoff 2 get; 1 move R_wing relocate",
			"2 dribble high_post drive_middle; 5 screen 1 R_slot flare; 1 move R_corner flare",
			"5 move rim slip",
		],
		options: [
			"1 three catch_and_shoot R_corner 3 2 kickout OffScreen 3",
			"5 rim layup rim 3 2 lob Cut 2",
			"2 mid pull_up high_post 2 - - Handoff 2",
			"4 three catch_and_shoot L_wing 3 2 skip Spotup 1",
			"3 three catch_and_shoot L_corner 3 2 skip Spotup 1",
		],
		risks: ["1 2 lost", "2 2 lost", "2 2 charge", "2 5 screen"],
	},
	{
		id: "get-dho",
		cat: "half",
		use: 7,
		start: "L_wing R_wing L_corner R_corner top*",
		needs:
			"shooter spacer | ballHandler shooter | shooter | shooter | handoffBig rollMan passer",
		steps: [
			"5 dribble R_slot advance",
			"5 handoff 2 get",
			"2 dribble high_post drive_middle; 5 move rim roll",
		],
		options: [
			"2 three pull_up R_slot 1 5 - Handoff 3",
			"2 mid pull_up high_post 2 - - Handoff 2",
			"2 rim layup rim 2 - - Handoff 2 | 5 move R_dunker seal; 2 dribble rim attack",
			"5 rim dunk rim 2 2 pocket Cut 2",
			"4 three catch_and_shoot R_corner 2 2 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 2 2 skip Spotup 1",
			"1 three catch_and_shoot L_wing 2 2 skip Spotup 1",
			"5 post hook R_lane 1 2 bounce Cut 1 | 2 dribble high_post drive_middle; 5 move R_lane roll",
		],
		risks: ["1 2 lost", "2 2 lost", "2 2 charge"],
	},
	{
		id: "dho-keep",
		cat: "half",
		use: 3,
		start: "L_wing R_wing L_corner R_corner top*",
		needs:
			"shooter | shooter cutter | shooter | shooter | handoffBig ballHandler big",
		steps: [
			"5 dribble R_slot advance",
			"5 handoff 2 fake",
			"5 dribble R_lane attack; 2 move top relocate",
		],
		options: [
			"5 post hook R_lane 2 - - Isolation 2",
			"5 rim layup rim 2 - - Isolation 2 | 5 dribble rim attack",
			"2 three catch_and_shoot top 2 5 kickout Spotup 2",
			"4 three catch_and_shoot R_corner 2 5 kickout Spotup 1",
			"1 three catch_and_shoot L_wing 2 5 skip Spotup 1",
		],
		risks: ["1 2 lost", "2 5 lost", "2 5 charge"],
	},
	{
		id: "delay-backdoor",
		cat: "half",
		use: 4,
		start: "L_wing* R_wing L_corner R_corner top",
		needs: "passer | cutter shooter | shooter | shooter | passer handoffBig",
		steps: ["1 pass 5 chest", "2 move R_slot v_cut", "2 move rim backdoor"],
		options: [
			"2 rim layup rim 2 5 bounce Cut 4",
			"2 mid pull_up R_elbow 1 - - Handoff 2 | 5 handoff 2 get; 2 dribble R_elbow attack",
			"4 three catch_and_shoot R_corner 2 5 skip Spotup 1",
			"3 three catch_and_shoot L_corner 2 5 skip Spotup 1",
		],
		risks: ["0 1 pass"],
	},
	{
		id: "delay-chicago",
		cat: "half",
		use: 4,
		start: "L_slot* R_corner R_wing L_corner top",
		needs:
			"passer shooter | ballHandler shooter | screener shooter | shooter | handoffBig passer rollMan",
		steps: [
			"1 pass 5 chest",
			"3 screen 2 R_short_corner pin_down; 2 move R_wing v_cut",
			"5 dribble R_slot advance; 5 handoff 2 get",
			"2 dribble high_post drive_middle; 5 move rim roll; 3 move R_corner pop",
		],
		options: [
			"2 three pull_up R_slot 2 5 - Handoff 3",
			"2 mid pull_up high_post 3 - - Handoff 2",
			"5 rim dunk rim 3 2 pocket Cut 2",
			"3 three catch_and_shoot R_corner 3 2 kickout Spotup 1",
			"4 three catch_and_shoot L_corner 3 2 skip Spotup 1",
			"1 three catch_and_shoot L_slot 3 2 kickout Spotup 1",
		],
		risks: ["0 1 pass", "1 3 screen", "2 2 lost", "3 2 lost", "3 2 charge"],
	},
	{
		id: "delay-split",
		cat: "half",
		use: 2,
		start: "L_slot* R_slot L_corner R_corner high_post",
		needs: "screener shooter | cutter shooter | shooter | shooter | passer big",
		steps: [
			"1 pass 5 chest",
			"1 screen 2 R_slot down",
			"2 move R_lane curl; 1 move top pop",
		],
		options: [
			"2 rim layup rim 2 5 bounce Cut 2 | 2 move rim curl",
			"2 mid floater R_lane 2 5 dump_off OffScreen 1",
			"1 three catch_and_shoot top 2 5 kickout Spotup 3",
			"5 mid pull_up high_post 2 - - Isolation 1",
			"4 three catch_and_shoot R_corner 2 5 skip Spotup 1",
		],
		risks: ["0 1 pass", "1 1 screen"],
	},
	{
		id: "box-stagger",
		cat: "half",
		use: 3,
		start: "top* L_block R_block L_elbow R_elbow",
		needs:
			"passer ballHandler | shooter offBallShooter | screener shooter | screener big | screener big",
		steps: [
			"3+5 screen 2 R_block+R_elbow stagger; 2 move R_wing sprint",
			"4 screen 3 L_block down; 3 move L_wing v_cut",
		],
		options: [
			"2 three catch_and_shoot R_wing 0 1 chest OffScreen 4",
			"3 three catch_and_shoot L_wing 1 1 chest OffScreen 2",
			"5 rim layup rim 0 1 lob Cut 1 | 5 move rim slip",
			"2 mid catch_and_shoot R_elbow 0 1 chest OffScreen 1 | 5 move R_slot pop; 2 move R_elbow curl",
		],
		risks: ["0 3 screen", "1 4 screen"],
	},
	{
		id: "stack-pop-post",
		cat: "half",
		use: 2,
		start: "R_slot* R_dunker L_corner L_wing R_block",
		needs: "passer | shooter passer | shooter | shooter | screener postScorer",
		steps: [
			"5 screen 2 R_block down; 2 move R_wing v_cut",
			"1 pass 2 chest; 5 post R_block seal",
			"2 pass 5 entry; 2 move R_corner relocate",
		],
		options: [
			"2 three catch_and_shoot R_wing 0 1 chest OffScreen 2",
			"5 post hook R_block 2 2 - Postup 2",
			"5 post fadeaway R_block 2 - - Postup 2 | 5 post R_block back_down",
			"2 three catch_and_shoot R_corner 2 5 kickout Spotup 1",
			"4 three catch_and_shoot L_wing 2 5 skip Spotup 1",
		],
		risks: ["0 5 screen", "1 1 pass", "2 2 pass"],
	},
	{
		id: "elevator",
		cat: "half",
		use: 3,
		start: "R_wing* R_lane L_corner high_post R_elbow",
		needs:
			"passer | shooter offBallShooter | shooter | screener big | screener big",
		steps: ["4+5 screen 2 high_post+R_elbow elevator; 2 move top sprint"],
		options: [
			"2 three catch_and_shoot top 0 1 swing OffScreen 5",
			"4 rim layup rim 0 1 lob Cut 1 | 4 move rim slip",
			"3 three catch_and_shoot L_corner 0 1 skip Spotup 1",
			"2 mid pull_up high_post 0 - - OffScreen 1 | 1 pass 2 swing; 2 dribble high_post attack",
		],
		risks: ["0 4 screen"],
	},
	{
		id: "iverson-pnr",
		cat: "half",
		use: 4,
		start: "top* L_wing R_corner L_elbow R_elbow",
		needs:
			"passer | ballHandler shooter cutter | shooter | screener | screener rollMan",
		steps: [
			"4+5 screen 2 L_elbow+R_elbow iverson; 2 move R_wing iverson_cut",
			"1 pass 2 chest; 1 move L_wing relocate; 4 move L_slot pop",
			"5 screen 2 R_wing ball",
			"2 dribble high_post drive_middle; 5 move rim roll",
		],
		options: [
			"2 three catch_and_shoot R_wing 1 1 - OffScreen 2",
			"2 mid pull_up high_post 3 - - PRBallHandler 3",
			"5 rim dunk rim 3 2 pocket PRRollMan 2",
			"3 three catch_and_shoot R_corner 3 2 kickout Spotup 1",
			"4 three catch_and_shoot L_slot 3 2 skip Spotup 1",
			"1 three catch_and_shoot L_wing 3 2 skip Spotup 1",
		],
		risks: ["1 1 pass", "2 5 screen", "3 2 lost", "3 2 charge"],
	},
	{
		id: "iverson-post",
		cat: "half",
		use: 2,
		start: "top* L_wing R_corner L_elbow R_elbow",
		needs:
			"passer | passer shooter | shooter | screener stretchBig | screener postScorer",
		steps: [
			"4+5 screen 2 L_elbow+R_elbow iverson; 2 move R_wing iverson_cut",
			"1 pass 2 chest; 5 post R_block seal; 4 move top lift; 1 move L_wing relocate",
			"2 pass 5 entry",
			"5 post R_block back_down",
		],
		options: [
			"5 post hook R_block 2 2 - Postup 2",
			"5 post hook R_block 3 - - Postup 2",
			"5 post fadeaway R_block 3 - - Postup 1",
			"2 three catch_and_shoot R_wing 3 5 kickout Spotup 1",
			"4 three catch_and_shoot top 3 5 kickout Spotup 1",
			"3 three catch_and_shoot R_corner 3 5 kickout Spotup 1",
		],
		risks: ["1 1 pass", "2 2 pass", "3 5 lost", "3 5 travel"],
	},
	{
		id: "iverson-curl",
		cat: "half",
		use: 2,
		start: "top* L_wing L_corner L_elbow R_elbow",
		needs:
			"passer ballHandler | shooter cutter | cutter slasher | screener shooter | screener big",
		steps: [
			"4+5 screen 2 L_elbow+R_elbow iverson; 2 move R_wing iverson_cut",
			"4 screen 3 L_block down; 3 move L_lane curl",
		],
		options: [
			"3 mid floater L_lane 1 1 bounce OffScreen 2",
			"3 rim layup rim 1 1 bounce Cut 2 | 3 move rim curl",
			"2 three catch_and_shoot R_wing 0 1 chest OffScreen 2",
			"4 three catch_and_shoot L_wing 1 1 chest Spotup 1 | 4 move L_wing pop",
		],
		risks: ["1 4 screen"],
	},
	{
		id: "ucla-cut",
		cat: "half",
		use: 3,
		start: "top* R_wing L_wing L_block R_elbow",
		needs:
			"cutter ballHandler | passer shooter | shooter | big | screener stretchBig",
		steps: [
			"1 pass 2 chest",
			"5 screen 1 R_elbow rip; 1 move rim rip_cut",
			"1 move R_block seal; 5 move top pop",
			"2 pass 5 swing",
		],
		options: [
			"1 rim layup rim 1 2 lob Cut 3",
			"1 post fadeaway R_block 2 2 entry Postup 2",
			"5 three catch_and_shoot top 3 2 - Spotup 1",
			"3 three catch_and_shoot L_wing 3 5 swing Spotup 2",
		],
		risks: ["0 1 pass", "3 2 pass"],
	},
	{
		id: "hawk-cut",
		cat: "half",
		use: 2,
		start: "top* L_wing R_wing R_dunker L_elbow",
		needs: "ballHandler passer | cutter | shooter | big | screener stretchBig",
		steps: [
			"1 dribble L_slot advance; 5 screen 2 L_elbow back; 2 move rim rip_cut",
			"2 move L_block seal; 5 move top pop",
		],
		options: [
			"2 rim layup rim 0 1 lob Cut 3",
			"5 three catch_and_shoot top 1 1 swing Spotup 2",
			"2 post hook L_block 1 1 entry Postup 1",
			"3 three catch_and_shoot R_wing 1 1 skip Spotup 1",
			"4 rim dunk R_dunker 0 1 lob Cut 1",
		],
		risks: ["0 5 screen"],
	},
	{
		id: "rip-ball-screen",
		cat: "half",
		use: 3,
		start: "top* R_wing L_corner L_wing R_elbow",
		needs:
			"cutter shooter | ballHandler | shooter | shooter | screener rollMan",
		steps: [
			"1 pass 2 chest",
			"5 screen 1 R_elbow rip; 1 move rim rip_cut",
			"1 move R_corner clear_out; 5 screen 2 R_wing ball",
			"2 dribble high_post drive_middle; 5 move rim roll",
		],
		options: [
			"1 rim layup rim 1 2 lob Cut 2",
			"2 mid pull_up high_post 3 - - PRBallHandler 2",
			"5 rim dunk rim 3 2 pocket PRRollMan 2",
			"1 three catch_and_shoot R_corner 3 2 kickout Spotup 1",
			"4 three catch_and_shoot L_wing 3 2 skip Spotup 1",
			"3 three catch_and_shoot L_corner 3 2 skip Spotup 1",
		],
		risks: ["0 1 pass", "2 5 screen", "3 2 lost", "3 2 charge"],
	},
	{
		id: "flex-cut",
		cat: "half",
		use: 1,
		start: "L_slot* R_slot L_corner R_corner L_block",
		needs:
			"screener passer | passer ballHandler | cutter | shooter | screener stretchBig",
		steps: [
			"1 pass 2 swing",
			"5 screen 3 L_block flex; 3 move R_block sprint",
			"1 screen 5 L_block down; 5 move L_slot lift",
		],
		options: [
			"3 rim layup rim 1 2 bounce Cut 3 | 3 move rim sprint",
			"3 post hook R_block 1 2 entry Cut 1",
			"5 three catch_and_shoot L_slot 2 2 swing OffScreen 2",
			"4 three catch_and_shoot R_corner 2 2 kickout Spotup 1",
		],
		risks: ["0 1 pass", "2 1 screen"],
	},
	{
		id: "princeton-chin",
		cat: "half",
		use: 2,
		start: "L_slot* R_slot L_wing R_wing R_elbow",
		needs:
			"shooter | cutter shooter | wing | passer slasher | screener passer big",
		steps: [
			"1 pass 2 swing",
			"2 pass 4 chest",
			"5 screen 2 R_elbow back; 2 move rim rip_cut",
			"2 move R_corner clear_out; 5 screen 1 high_post flare; 1 move top drift",
			"5 move rim roll",
		],
		options: [
			"2 rim layup rim 2 4 lob Cut 3",
			"1 three catch_and_shoot top 3 4 swing OffScreen 2",
			"5 rim dunk rim 4 4 bounce Cut 1",
			"2 three catch_and_shoot R_corner 3 4 kickout Spotup 1",
			"4 rim layup rim 4 - - Isolation 1 | 4 dribble rim attack",
		],
		risks: ["0 1 pass", "1 2 pass", "2 5 screen", "3 5 screen"],
	},
	{
		id: "princeton-point",
		cat: "half",
		use: 1,
		start: "L_slot* R_slot R_wing L_wing L_block",
		needs:
			"ballHandler shooter | passer screener | shooter | cutter | passer handoffBig big",
		steps: [
			"1 pass 2 swing",
			"1 move L_corner shallow_cut; 5 move L_elbow lift; 2 dribble top advance",
			"2 pass 5 chest",
			"4 move rim backdoor",
			"4 move R_corner clear_out; 2 screen 1 L_short_corner pin_down; 1 move L_wing v_cut",
			"5 dribble L_slot advance; 5 handoff 1 get",
			"1 dribble high_post attack; 5 move rim roll; 2 move L_corner pop",
		],
		options: [
			"4 rim layup rim 3 5 bounce Cut 3",
			"1 three pull_up L_slot 5 5 - Handoff 2",
			"1 mid pull_up high_post 6 - - Handoff 1",
			"5 rim dunk rim 6 1 pocket Cut 1",
			"2 three catch_and_shoot L_corner 6 1 kickout Spotup 1",
			"3 three catch_and_shoot R_wing 6 1 skip Spotup 1",
		],
		risks: [
			"0 1 pass",
			"2 2 pass",
			"4 2 screen",
			"5 1 lost",
			"6 1 lost",
			"6 1 charge",
		],
	},
	{
		id: "princeton-backdoor",
		cat: "half",
		use: 2,
		start: "top* R_slot L_wing R_wing high_post",
		needs: "ballHandler passer | shooter | cutter | cutter | passer big",
		steps: [
			"1 dribble L_slot advance; 3 move rim backdoor",
			"3 move R_dunker clear_out; 1 pass 5 chest",
			"4 move rim backdoor",
		],
		options: [
			"3 rim layup rim 0 1 bounce Cut 3",
			"4 rim layup rim 2 5 bounce Cut 3",
			"2 three catch_and_shoot R_slot 2 5 swing Spotup 1",
			"1 three catch_and_shoot L_slot 2 5 kickout Spotup 1",
			"5 mid pull_up high_post 2 - - Isolation 1",
		],
		risks: ["1 1 pass"],
	},
	{
		id: "five-out-pass-and-cut",
		cat: "half",
		use: 4,
		start: "top* R_wing L_wing R_corner L_corner",
		needs:
			"cutter ballHandler | passer ballHandler | shooter | shooter | shooter stretchBig",
		steps: [
			"1 pass 2 chest",
			"1 move rim sprint; 3 move top relocate; 5 move L_wing relocate",
			"1 move L_corner clear_out",
		],
		options: [
			"1 rim layup rim 1 2 bounce Cut 3",
			"3 three catch_and_shoot top 2 2 swing Spotup 2",
			"2 mid pull_up R_short_corner 2 - - Isolation 1 | 2 dribble R_short_corner drive_baseline",
			"4 three catch_and_shoot R_corner 2 2 kickout Spotup 1 | 2 dribble R_mid_wing attack",
			"1 three catch_and_shoot L_corner 2 3 swing Spotup 1 | 2 pass 3 swing",
		],
		risks: ["0 1 pass"],
	},
	{
		id: "split-action",
		cat: "half",
		use: 3,
		start: "R_wing* top L_wing L_corner R_block",
		needs:
			"screener cutter | shooter offBallShooter | shooter | shooter | postScorer passer big",
		steps: [
			"1 pass 5 entry",
			"1 screen 2 R_slot down; 2 move R_wing v_cut",
			"1 move rim slip",
		],
		options: [
			"2 three catch_and_shoot R_wing 1 5 kickout OffScreen 3",
			"1 rim layup rim 2 5 dump_off Cut 2",
			"5 post hook R_block 2 - - Postup 2 | 5 post R_block back_down",
			"3 three catch_and_shoot L_wing 2 5 skip Spotup 1",
		],
		risks: ["0 1 pass", "1 1 screen"],
	},
	{
		id: "drive-and-kick",
		cat: "half",
		use: 6,
		start: "top* R_wing L_wing R_corner L_dunker",
		needs: "ballHandler slasher | shooter | shooter | shooter | big rimRunner",
		steps: ["1 dribble R_lane drive_middle; 3 move top lift"],
		options: [
			"1 mid floater R_lane 0 - - Isolation 2",
			"1 rim layup rim 0 - - Isolation 2 | 1 dribble rim attack",
			"2 three catch_and_shoot R_wing 0 1 kickout Spotup 2",
			"4 three catch_and_shoot R_corner 0 2 swing Spotup 2 | 1 pass 2 kickout",
			"5 rim dunk L_dunker 0 1 dump_off Cut 2",
			"3 three catch_and_shoot top 0 1 kickout Spotup 1",
			"5 post hook L_lane 0 1 dump_off Cut 1 | 5 move L_lane flash",
		],
		risks: ["0 1 lost", "0 1 charge"],
	},
	{
		id: "triangle-sideline-post",
		cat: "half",
		use: 1,
		start: "R_corner R_wing* L_slot L_elbow R_block",
		needs: "shooter | passer cutter | shooter | big | postScorer passer",
		steps: [
			"2 pass 5 entry",
			"2 screen 1 R_short_corner down; 1 move R_wing v_cut",
			"2 move rim slip",
		],
		options: [
			"1 three catch_and_shoot R_wing 1 5 kickout OffScreen 2",
			"2 rim layup rim 2 5 dump_off Cut 2",
			"5 post hook R_block 2 - - Postup 3 | 5 post R_block back_down",
			"5 post fadeaway R_block 2 - - Postup 2",
			"3 three catch_and_shoot L_slot 2 5 skip Spotup 1",
		],
		risks: ["0 2 pass", "1 2 screen"],
	},
	{
		id: "triangle-blind-pig",
		cat: "half",
		use: 1,
		start: "R_corner R_wing* L_slot L_block R_block",
		needs: "shooter | passer | cutter | passer big | postScorer",
		steps: ["4 move high_post flash", "2 pass 4 chest; 3 move rim backdoor"],
		options: [
			"3 rim layup rim 1 4 bounce Cut 4",
			"4 mid pull_up high_post 1 - - Isolation 1",
			"5 post hook R_block 1 4 entry Postup 2",
		],
		risks: ["1 2 pass"],
	},
	{
		id: "triangle-solo-cut",
		cat: "half",
		use: 1,
		start: "R_corner R_wing* L_slot L_elbow R_block",
		needs: "shooter | passer cutter | shooter | big | postScorer",
		steps: [
			"1 move L_corner clear_out",
			"2 pass 5 entry",
			"2 move R_dunker v_cut",
		],
		options: [
			"2 rim layup R_dunker 2 5 dump_off Cut 2",
			"5 post hook R_block 2 - - Postup 3 | 5 post R_block back_down",
			"5 post fadeaway R_block 2 - - Postup 2",
			"3 three catch_and_shoot L_slot 2 5 skip Spotup 1",
			"1 three catch_and_shoot L_corner 2 5 skip Spotup 1",
		],
		risks: ["1 2 pass"],
	},
	{
		id: "triangle-center-opposite",
		cat: "half",
		use: 1,
		start: "R_corner R_wing* L_slot L_elbow R_block",
		needs: "shooter | passer | passer | passer shooter | postScorer",
		steps: [
			"5 post L_block seal; 4 move L_wing lift",
			"2 pass 3 swing",
			"3 pass 4 chest",
			"4 pass 5 entry",
		],
		options: [
			"5 post hook L_block 3 4 - Postup 3",
			"5 post fadeaway L_block 3 - - Postup 2 | 5 post L_block back_down",
			"4 three catch_and_shoot L_wing 3 5 kickout Spotup 1",
			"2 three catch_and_shoot R_wing 3 5 skip Spotup 1",
		],
		risks: ["1 2 pass", "2 3 pass", "3 4 pass"],
	},
	{
		id: "weave-into-pnr",
		cat: "half",
		use: 3,
		start: "L_slot* R_slot R_corner L_corner high_post",
		needs:
			"ballHandler | ballHandler shooter | ballHandler shooter | shooter | screener rollMan",
		steps: [
			"1 dribble top advance; 1 handoff 2 get; 1 move L_wing relocate",
			"2 dribble R_slot advance; 3 move R_wing v_cut; 2 handoff 3 get; 2 move R_corner clear_out",
			"5 screen 3 R_slot ball",
			"3 dribble high_post drive_middle; 5 move rim roll",
		],
		options: [
			"2 three pull_up top 0 1 - Handoff 1",
			"3 three pull_up R_slot 1 2 - Handoff 2",
			"3 mid pull_up high_post 3 - - PRBallHandler 2",
			"5 rim dunk rim 3 3 pocket PRRollMan 2",
			"2 three catch_and_shoot R_corner 3 3 kickout Spotup 1",
			"1 three catch_and_shoot L_wing 3 3 skip Spotup 1",
			"4 three catch_and_shoot L_corner 3 3 skip Spotup 1",
		],
		risks: ["0 2 lost", "1 3 lost", "2 5 screen", "3 3 lost", "3 3 charge"],
	},
	{
		id: "weave-lob",
		cat: "half",
		use: 2,
		start: "L_slot* R_slot R_corner L_corner high_post",
		needs:
			"cutter lobThreat | ballHandler passer | shooter | shooter | screener stretchBig",
		steps: [
			"1 dribble top advance; 1 handoff 2 get",
			"2 dribble R_slot advance; 5 screen 1 high_post back; 1 move rim backdoor",
			"5 move top pop",
		],
		options: [
			"1 rim alley_oop rim 1 2 lob Cut 3",
			"5 three catch_and_shoot top 2 2 swing Spotup 2",
			"2 three pull_up top 0 1 - Handoff 1",
			"3 three catch_and_shoot R_corner 2 2 kickout Spotup 1",
		],
		risks: ["0 2 lost", "1 5 screen"],
	},
	{
		id: "pin-down",
		cat: "half",
		use: 6,
		start: "top* R_dunker L_wing L_corner R_elbow",
		needs: "passer | shooter offBallShooter | shooter | shooter | screener big",
		steps: ["5 screen 2 R_block pin_down", "2 move R_wing v_cut"],
		options: [
			"2 three catch_and_shoot R_wing 1 1 chest OffScreen 4",
			"2 mid catch_and_shoot R_elbow 0 1 chest OffScreen 2 | 2 move R_elbow curl",
			"2 mid floater R_lane 0 1 bounce OffScreen 1 | 2 move R_lane curl",
			"2 three catch_and_shoot R_corner 0 1 skip OffScreen 1 | 2 move R_corner fade",
			"2 rim layup rim 0 1 lob Cut 1 | 2 move rim backdoor",
			"5 rim dunk rim 1 1 lob Cut 1 | 5 move rim slip",
		],
		risks: ["0 5 screen"],
	},
	{
		id: "flare-screen",
		cat: "half",
		use: 5,
		start: "top* L_slot R_corner L_elbow R_dunker",
		needs:
			"ballHandler passer | shooter offBallShooter | shooter | screener big | big",
		steps: [
			"1 dribble R_slot advance; 4 screen 2 L_slot flare; 2 move L_wing flare",
			"4 move rim slip",
		],
		options: [
			"2 three catch_and_shoot L_wing 0 1 skip OffScreen 4",
			"4 rim layup rim 1 1 lob Cut 2",
			"1 mid pull_up R_elbow 0 - - Isolation 1 | 1 dribble R_elbow attack",
			"3 three catch_and_shoot R_corner 1 1 kickout Spotup 1",
		],
		risks: ["0 4 screen"],
	},
	{
		id: "back-screen-lob",
		cat: "half",
		use: 4,
		start: "R_slot* R_corner L_wing R_dunker L_elbow",
		needs:
			"passer ballHandler | shooter | cutter lobThreat | big | screener stretchBig",
		steps: ["5 screen 3 L_elbow back; 3 move rim backdoor", "5 move top pop"],
		options: [
			"3 rim alley_oop rim 0 1 lob Cut 3",
			"5 three catch_and_shoot top 1 1 swing Spotup 2",
			"4 rim dunk R_dunker 0 1 lob Cut 1",
			"2 three catch_and_shoot R_corner 1 1 kickout Spotup 1",
		],
		risks: ["0 5 screen"],
	},
	{
		id: "cross-screen-post",
		cat: "half",
		use: 3,
		start: "R_wing* top L_corner R_block L_block",
		needs: "passer | shooter | shooter | screener stretchBig | postScorer big",
		steps: [
			"4 screen 5 L_lane cross; 5 post R_block seal",
			"1 pass 5 entry",
			"4 move L_elbow lift; 5 post R_block back_down",
		],
		options: [
			"5 post hook R_block 1 1 - Postup 3",
			"5 post fadeaway R_block 2 - - Postup 2",
			"5 rim layup rim 2 - - Postup 1 | 5 post rim up_and_under",
			"4 mid catch_and_shoot L_elbow 2 5 kickout Spotup 1",
			"1 three catch_and_shoot R_wing 2 5 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 2 5 skip Spotup 1",
		],
		risks: ["0 4 screen", "1 1 pass", "2 5 lost", "2 5 travel"],
	},
	{
		id: "loop-dho",
		cat: "half",
		use: 2,
		start: "R_slot* L_wing R_corner L_corner L_elbow",
		needs:
			"passer shooter | ballHandler shooter | shooter | shooter | handoffBig rollMan",
		steps: [
			"1 pass 5 chest",
			"2 move L_block v_cut",
			"5 handoff 2 get",
			"2 dribble high_post attack; 5 move rim roll",
		],
		options: [
			"2 mid pull_up L_elbow 2 5 - Handoff 3",
			"2 rim layup rim 3 - - Handoff 2 | 2 dribble rim attack",
			"5 rim dunk rim 3 2 pocket Cut 2",
			"4 three catch_and_shoot L_corner 3 2 kickout Spotup 1",
			"1 three catch_and_shoot R_slot 3 2 kickout Spotup 1",
			"3 three catch_and_shoot R_corner 3 2 skip Spotup 1",
		],
		risks: ["0 1 pass", "2 2 lost", "3 2 lost", "3 2 charge"],
	},
	{
		id: "twirl",
		cat: "half",
		use: 2,
		start: "top* L_wing L_dunker R_corner R_elbow",
		needs: "passer | shooter screener | shooter screener | shooter | big",
		steps: [
			"2 screen 3 L_block down; 3 move L_mid_wing curl",
			"3 screen 2 L_block down; 2 move L_wing v_cut",
			"3 move L_corner pop",
		],
		options: [
			"2 three catch_and_shoot L_wing 1 1 chest OffScreen 4",
			"3 mid catch_and_shoot L_mid_wing 0 1 chest OffScreen 1",
			"3 three catch_and_shoot L_corner 2 1 skip Spotup 2",
			"3 rim layup rim 1 1 lob Cut 1 | 3 move rim slip",
		],
		risks: ["0 2 screen", "1 3 screen"],
	},
	{
		id: "wedge-step-up",
		cat: "half",
		use: 2,
		start: "R_wing* high_post L_corner R_corner L_block",
		needs:
			"ballHandler | screener shooter | shooter | shooter | screener rollMan",
		steps: [
			"2 screen 5 high_post wedge; 5 move R_elbow sprint",
			"5 screen 1 R_wing step_up; 2 move top pop",
			"1 dribble high_post drive_middle; 5 move rim roll",
		],
		options: [
			"5 rim dunk rim 2 1 pocket PRRollMan 3",
			"1 mid pull_up high_post 2 - - PRBallHandler 2",
			"2 three catch_and_shoot top 2 1 kickout Spotup 2",
			"4 three catch_and_shoot R_corner 2 1 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 2 1 skip Spotup 1",
		],
		risks: ["1 5 screen", "2 1 lost", "2 1 charge"],
	},
	{
		id: "stagger-away",
		cat: "half",
		use: 3,
		start: "R_slot* L_dunker R_corner L_block L_elbow",
		needs:
			"passer | shooter offBallShooter | shooter | screener postScorer | screener big",
		steps: ["4+5 screen 2 L_block+L_elbow stagger; 2 move L_slot sprint"],
		options: [
			"2 three catch_and_shoot L_slot 0 1 swing OffScreen 4",
			"2 mid floater L_lane 0 1 bounce OffScreen 1 | 2 move L_lane curl",
			"5 rim layup rim 0 1 lob Cut 1 | 5 move rim slip",
			"4 post hook L_block 0 1 entry Postup 1",
			"3 three catch_and_shoot R_corner 0 1 kickout Spotup 1",
		],
		risks: ["0 4 screen"],
	},
	{
		id: "iso-top-clear",
		cat: "half",
		use: 7,
		start: "top* R_corner L_corner L_wing R_dunker",
		needs:
			"isoScorer ballHandler | shooter spacer | shooter spacer | shooter spacer | big rimRunner",
		steps: ["1 dribble top hesitation", "1 dribble R_elbow crossover"],
		options: [
			"1 three step_back top 0 - - Isolation 3 | 1 dribble top step_back",
			"1 mid pull_up R_elbow 1 - - Isolation 3",
			"1 rim layup rim 1 - - Isolation 2 | 1 dribble rim attack",
			"1 mid fadeaway R_elbow 1 - - Isolation 1",
			"5 rim dunk R_dunker 1 1 dump_off Cut 1",
			"2 three catch_and_shoot R_corner 1 1 kickout Spotup 1",
		],
		risks: ["1 1 lost"],
	},
	{
		id: "iso-wing-clear",
		cat: "half",
		use: 5,
		start: "L_slot R_wing* L_corner L_wing L_dunker",
		needs: "shooter spacer | isoScorer | shooter | shooter | big rimRunner",
		steps: ["2 dribble R_mid_wing attack"],
		options: [
			"2 mid pull_up R_mid_wing 0 - - Isolation 3",
			"2 mid fadeaway R_mid_wing 0 - - Isolation 2",
			"2 three step_back R_wing 0 - - Isolation 2 | 2 dribble R_wing step_back",
			"2 rim layup rim 0 - - Isolation 2 | 2 dribble R_short_corner drive_baseline; 2 dribble rim drive_baseline",
			"5 rim dunk L_dunker 0 2 dump_off Cut 1 | 2 dribble R_lane attack",
			"1 three catch_and_shoot L_slot 0 2 kickout Spotup 1",
			"2 post fadeaway R_block 0 - - Isolation 1 | 2 post R_block back_down",
		],
		risks: ["0 2 lost"],
	},
	{
		id: "iso-switch-hunt",
		cat: "half",
		use: 5,
		start: "top* R_wing L_corner R_elbow L_dunker",
		needs:
			"isoScorer ballHandler | shooter | shooter | screener shooter | big rimRunner",
		steps: [
			"4 screen 1 top ball",
			"4 move R_corner clear_out; 1 dribble top hesitation",
			"1 dribble L_elbow crossover",
		],
		options: [
			"1 three step_back top 1 - - Isolation 3 | 1 dribble top step_back",
			"1 mid pull_up L_elbow 2 - - Isolation 2",
			"1 rim layup rim 2 - - Isolation 2 | 1 dribble rim attack",
			"5 rim dunk L_dunker 2 1 dump_off Cut 1",
			"3 three catch_and_shoot L_corner 2 1 kickout Spotup 1",
		],
		risks: ["0 4 screen", "2 1 lost"],
	},
	{
		id: "iso-post-mismatch",
		cat: "half",
		use: 4,
		start: "R_wing* L_corner L_wing R_block top",
		needs: "passer | shooter | shooter | postScorer | stretchBig spacer",
		steps: [
			"4 post R_block seal",
			"1 pass 4 entry",
			"4 post R_block back_down",
		],
		options: [
			"4 post hook R_block 1 1 - Postup 2",
			"4 post fadeaway R_block 2 - - Postup 3",
			"4 rim dunk rim 2 - - Postup 2 | 4 post rim drop_step",
			"1 three catch_and_shoot R_wing 2 4 kickout Spotup 1",
			"5 three catch_and_shoot top 2 4 kickout Spotup 1",
			"3 three catch_and_shoot L_wing 2 4 skip Spotup 1",
		],
		risks: ["1 1 pass", "2 4 lost", "2 4 travel"],
	},
	{
		id: "iso-1-4-flat",
		cat: "half",
		use: 3,
		start: "top* R_corner L_corner R_dunker L_dunker",
		needs: "isoScorer ballHandler | shooter | shooter | big | big rimRunner",
		steps: ["1 dribble top hesitation", "1 dribble L_lane drive_middle"],
		options: [
			"1 mid floater L_lane 1 - - Isolation 2",
			"1 rim layup rim 1 - - Isolation 2 | 1 dribble rim attack",
			"1 three pull_up top 0 - - Isolation 2",
			"1 mid pull_up high_post 0 - - Isolation 1 | 1 dribble high_post attack",
			"5 rim dunk L_dunker 1 1 dump_off Cut 1",
			"3 three catch_and_shoot L_corner 1 1 kickout Spotup 1",
		],
		risks: ["1 1 lost", "1 1 charge"],
	},
	{
		id: "post-up-wing-entry",
		cat: "half",
		use: 4,
		start: "R_wing* R_corner L_wing L_corner R_block",
		needs:
			"passer shooter | shooter | shooter | shooter spacer | postScorer passer",
		steps: [
			"5 post R_block seal",
			"1 pass 5 entry; 1 move R_slot relocate",
			"5 post R_block back_down",
		],
		options: [
			"5 post hook R_block 2 - - Postup 4",
			"5 post fadeaway R_block 2 - - Postup 2",
			"5 rim layup rim 2 - - Postup 2 | 5 post rim drop_step",
			"1 three catch_and_shoot R_slot 2 5 kickout Spotup 1",
			"2 three catch_and_shoot R_corner 2 5 kickout Spotup 1",
			"3 three catch_and_shoot L_wing 2 5 skip Spotup 1",
			"4 three catch_and_shoot L_corner 2 1 skip Spotup 1 | 5 pass 1 kickout",
		],
		risks: ["1 1 pass", "2 5 lost", "2 5 travel"],
	},
	{
		id: "high-low",
		cat: "half",
		use: 2,
		start: "L_slot* R_wing L_corner high_post R_block",
		needs:
			"passer | shooter | shooter | passer stretchBig | postScorer lobThreat",
		steps: ["1 pass 4 chest", "5 post R_dunker seal"],
		options: [
			"5 rim layup R_dunker 1 4 lob Postup 3",
			"4 mid pull_up high_post 1 - - Isolation 2",
			"2 three catch_and_shoot R_wing 1 4 kickout Spotup 1",
			"1 three catch_and_shoot L_slot 1 4 kickout Spotup 1",
		],
		risks: ["0 1 pass"],
	},
	{
		id: "guard-post-up",
		cat: "half",
		use: 2,
		start: "top* R_wing L_wing L_corner R_elbow",
		needs: "passer | postScorer isoScorer | shooter | shooter | stretchBig",
		steps: [
			"2 post R_block seal",
			"1 pass 2 entry",
			"2 post R_block back_down",
		],
		options: [
			"2 post fadeaway R_block 2 - - Postup 4",
			"2 rim layup rim 2 - - Postup 1 | 2 post rim drop_step",
			"5 mid catch_and_shoot R_elbow 2 2 kickout Spotup 1",
			"1 three catch_and_shoot top 2 2 kickout Spotup 1",
			"4 three catch_and_shoot L_corner 2 2 skip Spotup 1",
		],
		risks: ["1 1 pass", "2 2 lost", "2 2 travel"],
	},
	{
		id: "transition-fill-lanes",
		cat: "break",
		use: 9,
		start: "own_L_outlet own_R_outlet backcourt_L backcourt_mid own_rim*",
		needs:
			"ballHandler | shooter wing | shooter wing | rimRunner big | rebounder big passer",
		steps: [
			"5 pass 1 outlet; 2 move backcourt_R sprint; 3 move L_hash sprint; 4 move high_post sprint",
			"1 dribble backcourt_mid advance; 2 move R_corner sprint; 3 move L_corner sprint; 4 move rim sprint; 5 move backcourt_L jog",
			"1 dribble R_slot advance; 5 move top jog",
		],
		options: [
			"4 rim dunk rim 2 1 lob Transition 3",
			"1 rim layup rim 2 - - Transition 3 | 4 move L_dunker seal; 1 dribble rim attack",
			"1 three pull_up R_slot 2 - - Transition 2",
			"2 three catch_and_shoot R_corner 2 1 kickout Transition 2",
			"3 three catch_and_shoot L_corner 2 1 skip Transition 1",
			"5 three catch_and_shoot top 2 1 swing Transition 1",
			"4 post hook L_lane 1 1 bounce Transition 1 | 4 move L_lane seal",
		],
		risks: ["0 5 pass"],
	},
	{
		id: "transition-3-on-2",
		cat: "break",
		use: 5,
		start: "backcourt_mid* backcourt_R backcourt_L own_R_outlet own_rim",
		needs: "ballHandler passer | wing slasher | wing shooter | big | big",
		steps: [
			"1 dribble top advance; 2 move R_wing sprint; 3 move L_wing sprint; 4 move backcourt_R sprint; 5 move own_L_outlet jog",
			"1 dribble high_post attack; 2 move R_dunker sprint; 3 move L_corner sprint; 4 move R_hash sprint",
		],
		options: [
			"2 rim layup R_dunker 1 1 bounce Transition 3",
			"1 mid pull_up high_post 1 - - Transition 2",
			"1 rim layup rim 1 - - Transition 2 | 1 dribble rim attack",
			"3 three catch_and_shoot L_corner 1 1 skip Transition 2",
			"4 three catch_and_shoot R_hash 1 1 swing Transition 1",
		],
		risks: ["1 1 lost", "1 1 charge"],
	},
	{
		id: "transition-2-on-1",
		cat: "break",
		use: 4,
		start: "backcourt_mid* backcourt_R own_L_outlet own_rim own_R_outlet",
		needs: "ballHandler | wing slasher | wing | big | big",
		steps: [
			"1 dribble top advance; 2 move R_wing sprint; 3 move backcourt_L jog",
			"1 dribble R_lane attack; 2 move R_dunker sprint",
		],
		options: [
			"2 rim dunk R_dunker 1 1 bounce Transition 4",
			"1 rim layup rim 1 - - Transition 3 | 1 dribble rim attack",
			"1 mid floater R_lane 1 - - Transition 1",
		],
		risks: ["1 1 lost", "1 1 charge"],
	},
	{
		id: "transition-steal-breakaway",
		cat: "break",
		use: 5,
		start: "own_L_outlet backcourt_L* own_R_outlet own_rim backcourt_R",
		needs: "wing | slasher wing | wing | big | big",
		steps: [
			"2 dribble L_hash advance; 5 move R_hash sprint; 1 move backcourt_mid sprint",
			"2 dribble rim attack; 1 move top sprint",
		],
		options: [
			"2 rim dunk rim 1 - - Transition 5",
			"2 rim layup rim 1 - - Transition 2",
			"5 rim dunk rim 0 2 overhead Transition 1 | 5 move rim sprint",
			"1 three catch_and_shoot top 1 2 kickout Transition 1",
		],
		risks: ["1 2 lost", "1 2 charge"],
	},
	{
		id: "transition-pitch-ahead",
		cat: "break",
		use: 4,
		start: "own_L_outlet* backcourt_R L_hash backcourt_mid own_rim",
		needs:
			"passer ballHandler | shooter wing | shooter wing | rimRunner | rebounder big",
		steps: [
			"1 pass 3 overhead; 2 move R_hash sprint; 4 move high_post sprint",
			"3 dribble L_wing advance; 2 move R_corner sprint; 4 move rim sprint",
		],
		options: [
			"3 three catch_and_shoot L_hash 0 1 - Transition 1",
			"3 three pull_up L_wing 1 - - Transition 3",
			"2 three catch_and_shoot R_corner 1 3 skip Transition 2",
			"4 rim dunk rim 1 3 lob Transition 2",
			"3 rim layup rim 1 - - Transition 1 | 3 dribble rim attack",
		],
		risks: ["0 1 pass"],
	},
	{
		id: "transition-trailer-three",
		cat: "break",
		use: 4,
		start: "L_hash* R_corner L_corner R_dunker backcourt_mid",
		needs: "ballHandler | shooter | shooter | rimRunner | stretchBig popBig",
		steps: ["1 dribble L_wing advance; 5 move top jog"],
		options: [
			"5 three catch_and_shoot top 0 1 swing Transition 4",
			"2 three catch_and_shoot R_corner 0 5 swing Transition 2 | 1 pass 5 swing",
			"5 rim layup rim 0 - - Transition 1 | 1 pass 5 swing; 5 dribble rim attack",
			"4 rim dunk R_dunker 0 1 lob Transition 1",
		],
		risks: [],
	},
	{
		id: "transition-early-post",
		cat: "break",
		use: 3,
		start: "L_hash* R_corner L_corner L_lane backcourt_mid",
		needs:
			"ballHandler passer | shooter | shooter | rimRunner postScorer | stretchBig",
		steps: [
			"1 dribble L_wing advance; 4 post L_block seal; 5 move top jog",
			"1 pass 4 entry",
		],
		options: [
			"4 post hook L_block 1 1 - Postup 3",
			"4 rim dunk rim 1 - - Transition 3 | 4 post rim drop_step",
			"5 three catch_and_shoot top 1 4 kickout Transition 1",
			"3 three catch_and_shoot L_corner 1 4 kickout Transition 1",
		],
		risks: ["1 1 pass"],
	},
	{
		id: "oreb-putback",
		cat: "half",
		use: 6,
		start: "top R_corner L_wing L_dunker rim*",
		needs: "shooter | shooter | shooter | rebounder big | rebounder big",
		steps: ["2 move R_wing relocate; 3 move L_slot relocate"],
		options: [
			"5 rim putback rim 0 - - Putback 5",
			"2 three catch_and_shoot R_wing 0 5 kickout Spotup 2",
			"3 three catch_and_shoot L_slot 0 5 kickout Spotup 1",
			"4 rim dunk L_dunker 0 5 dump_off Putback 1",
			"5 post hook R_lane 0 - - Putback 1 | 5 post R_lane hook",
		],
		risks: [],
	},
	{
		id: "long-rebound-attack",
		cat: "half",
		use: 3,
		start: "top R_slot* L_corner L_dunker R_block",
		needs: "shooter | ballHandler slasher | shooter | big | big",
		steps: ["1 move L_wing relocate", "2 dribble R_lane attack"],
		options: [
			"2 three pull_up R_slot 0 - - Misc 2",
			"2 mid floater R_lane 1 - - Misc 2",
			"4 rim dunk L_dunker 1 2 dump_off Cut 1",
			"3 three catch_and_shoot L_corner 1 2 kickout Spotup 1",
			"1 three catch_and_shoot L_wing 1 2 kickout Spotup 1",
		],
		risks: ["1 2 lost", "1 2 charge"],
	},
	{
		id: "broken-play-swing",
		cat: "half",
		use: 6,
		start: "top R_wing* L_wing R_corner L_corner",
		needs:
			"shooter passer | ballHandler slasher | shooter slasher | shooter | shooter stretchBig",
		steps: [
			"2 dribble R_lane drive_middle",
			"2 pass 1 kickout",
			"1 pass 3 swing",
			"3 dribble L_lane attack",
		],
		options: [
			"1 three catch_and_shoot top 1 2 - Spotup 2",
			"3 three catch_and_shoot L_wing 2 1 - Spotup 3",
			"3 mid floater L_lane 3 - - Spotup 2",
			"5 three catch_and_shoot L_corner 3 3 kickout Spotup 2",
			"4 three catch_and_shoot R_corner 0 2 kickout Spotup 1",
		],
		risks: [
			"0 2 lost",
			"0 2 charge",
			"1 2 pass",
			"2 1 pass",
			"3 3 lost",
			"3 3 charge",
		],
	},
	{
		id: "blob-box-cross",
		cat: "blob",
		use: 5,
		start: "L_elbow inbound_baseline_R* R_elbow L_block R_block",
		needs:
			"screener shooter | inbounder passer | shooter ballHandler | cutter big | screener shooter",
		steps: [
			"5 screen 4 L_lane cross; 4 move R_dunker flash",
			"1 screen 5 L_lane down; 5 move L_elbow lift; 3 move top pop",
		],
		options: [
			"4 rim layup R_dunker 0 2 inbound Cut 3",
			"5 mid catch_and_shoot L_elbow 1 2 inbound OffScreen 2",
			"3 three catch_and_shoot top 1 2 inbound Spotup 1",
			"1 post hook L_lane 1 2 inbound Postup 1",
		],
		risks: ["0 5 screen", "1 1 screen", "0 2 fiveSeconds"],
	},
	{
		id: "blob-stack",
		cat: "blob",
		use: 4,
		start: "inbound_baseline_R* R_elbow R_mid_wing R_lane R_block",
		needs:
			"inbounder passer | ballHandler shooter | shooter | cutter | postScorer big",
		steps: [
			"2 move top pop; 3 move R_corner pop; 4 move L_dunker curl; 5 post R_block seal",
		],
		options: [
			"3 three catch_and_shoot R_corner 0 1 inbound Spotup 3",
			"5 post hook R_block 0 1 inbound Postup 2",
			"4 rim layup L_dunker 0 1 lob Cut 2",
			"2 three catch_and_shoot top 0 1 inbound Spotup 1",
		],
		risks: ["0 1 fiveSeconds"],
	},
	{
		id: "blob-line",
		cat: "blob",
		use: 3,
		start: "inbound_baseline_R* R_mid_wing L_elbow high_post R_elbow",
		needs:
			"inbounder passer | shooter | ballHandler shooter | cutter lobThreat | screener postScorer",
		steps: [
			"2 move R_corner v_cut; 5 screen 4 R_elbow back; 4 move rim backdoor; 3 move top pop",
			"5 post R_block seal",
		],
		options: [
			"4 rim alley_oop rim 0 1 lob Cut 3",
			"2 three catch_and_shoot R_corner 0 1 inbound Spotup 2",
			"5 post hook R_block 1 1 inbound Postup 2",
			"3 three catch_and_shoot top 0 1 inbound Spotup 1",
		],
		risks: ["0 5 screen", "0 1 fiveSeconds"],
	},
	{
		id: "blob-zipper",
		cat: "blob",
		use: 3,
		start: "R_elbow L_block inbound_baseline_L* R_block L_elbow",
		needs:
			"ballHandler | shooter offBallShooter | inbounder passer | cutter big | screener postScorer",
		steps: [
			"5 screen 2 L_lane zipper; 2 move L_slot sprint; 1 move R_slot pop",
			"5 post L_block seal",
		],
		options: [
			"2 three catch_and_shoot L_slot 0 3 inbound OffScreen 3",
			"5 post hook L_block 1 3 inbound Postup 2",
			"4 rim layup rim 0 3 lob Cut 1 | 4 move rim flash",
			"1 three catch_and_shoot R_slot 0 3 inbound Spotup 1",
		],
		risks: ["0 3 fiveSeconds"],
	},
	{
		id: "blob-exit",
		cat: "blob",
		use: 3,
		start: "R_elbow inbound_baseline_R* L_elbow L_block R_block",
		needs:
			"ballHandler passer | inbounder shooter offBallShooter | shooter | big | screener postScorer",
		steps: [
			"1 move top v_cut; 2 pass 1 inbound",
			"5 screen 2 R_short_corner pin_down; 2 move R_wing sprint; 3 move L_wing pop",
		],
		options: [
			"2 three catch_and_shoot R_wing 1 1 swing OffScreen 4",
			"5 post hook R_block 1 1 entry Postup 1 | 5 post R_block seal",
			"3 three catch_and_shoot L_wing 1 1 swing Spotup 1",
		],
		risks: ["0 2 pass", "1 5 screen", "0 2 fiveSeconds"],
	},
	{
		id: "blob-shooting-big-curl",
		cat: "blob",
		use: 3,
		start: "inbound_baseline_R* L_block L_elbow R_block R_elbow",
		needs:
			"inbounder passer | cutter lobThreat | screener shooter | popBig stretchBig | screener postScorer",
		steps: [
			"5 screen 4 R_lane down; 4 move R_slot pop; 3 screen 2 L_lane down; 2 move rim curl",
		],
		options: [
			"4 three catch_and_shoot R_slot 0 1 inbound OffScreen 3",
			"2 rim layup rim 0 1 lob Cut 3",
			"5 post hook R_block 0 1 inbound Postup 1 | 5 post R_block seal",
			"3 three catch_and_shoot top 0 1 inbound Spotup 1 | 3 move top pop",
		],
		risks: ["0 5 screen", "0 3 screen", "0 1 fiveSeconds"],
	},
	{
		id: "slob-box-pindown",
		cat: "slob",
		use: 4,
		start: "inbound_sideline_R* L_block R_block L_elbow R_elbow",
		needs:
			"inbounder passer | shooter ballHandler | shooter | screener | screener rollMan",
		steps: [
			"5 screen 3 R_lane pin_down; 3 move R_wing v_cut; 4 screen 2 L_lane pin_down; 2 move top v_cut",
		],
		options: [
			"3 three catch_and_shoot R_wing 0 1 inbound OffScreen 3",
			"2 three catch_and_shoot top 0 1 inbound OffScreen 2",
			"5 rim layup rim 0 1 lob Cut 1 | 5 move rim slip",
		],
		risks: ["0 5 screen", "0 4 screen", "0 1 fiveSeconds"],
	},
	{
		id: "slob-line",
		cat: "slob",
		use: 3,
		start: "inbound_sideline_R* R_elbow high_post L_elbow L_mid_wing",
		needs:
			"inbounder passer | ballHandler shooter | cutter lobThreat | screener big | shooter",
		steps: [
			"2 move R_wing v_cut; 4 screen 3 high_post back; 3 move rim backdoor; 5 move L_slot pop",
			"4 post R_block seal",
		],
		options: [
			"3 rim alley_oop rim 0 1 lob Cut 2",
			"2 three catch_and_shoot R_wing 0 1 inbound Spotup 2",
			"5 three catch_and_shoot L_slot 0 1 inbound Spotup 1",
			"4 post hook R_block 1 1 inbound Postup 1",
		],
		risks: ["0 4 screen", "0 1 fiveSeconds"],
	},
	{
		id: "slob-elevator",
		cat: "slob",
		use: 2,
		start: "inbound_sideline_R* R_lane L_corner high_post R_elbow",
		needs:
			"inbounder passer | shooter offBallShooter | shooter | screener big | screener big",
		steps: ["5+4 screen 2 R_elbow+high_post elevator; 2 move R_slot sprint"],
		options: [
			"2 three catch_and_shoot R_slot 0 1 inbound OffScreen 4",
			"4 rim layup rim 0 1 lob Cut 1 | 4 move rim slip",
			"3 three catch_and_shoot L_corner 0 1 skip Spotup 1",
		],
		risks: ["0 5 screen", "0 1 fiveSeconds"],
	},
	{
		id: "slob-stack-pnr",
		cat: "slob",
		use: 3,
		start: "inbound_sideline_R* R_slot L_corner high_post R_elbow",
		needs:
			"inbounder shooter | ballHandler | shooter | shooter offBallShooter | screener rollMan",
		steps: [
			"2 move top v_cut; 1 pass 2 inbound",
			"1 move R_wing jog; 5 screen 2 top ball",
			"2 dribble L_elbow attack; 4 move R_slot pop; 5 move rim roll",
		],
		options: [
			"4 three catch_and_shoot R_slot 2 2 kickout Spotup 3",
			"5 rim dunk rim 2 2 pocket PRRollMan 2",
			"2 mid pull_up L_elbow 2 - - PRBallHandler 2",
			"3 three catch_and_shoot L_corner 2 2 kickout Spotup 1",
			"1 three catch_and_shoot R_wing 2 2 skip Spotup 1",
		],
		risks: ["0 1 pass", "1 5 screen", "2 2 lost", "0 1 fiveSeconds"],
	},
	{
		id: "slob-back-screen-lob",
		cat: "slob",
		use: 2,
		start: "inbound_sideline_R* L_slot R_corner R_wing L_elbow",
		needs:
			"inbounder passer | screener shooter | shooter | shooter | lobThreat big",
		steps: ["2 screen 5 L_elbow back; 5 move rim backdoor", "2 move top pop"],
		options: [
			"5 rim alley_oop rim 0 1 lob Cut 4",
			"2 three catch_and_shoot top 1 1 inbound Spotup 2",
			"4 three catch_and_shoot R_wing 0 1 inbound Spotup 1",
		],
		risks: ["0 2 screen", "0 1 fiveSeconds"],
	},
	{
		id: "slob-dho",
		cat: "slob",
		use: 4,
		start: "inbound_sideline_R* L_wing L_corner R_corner R_elbow",
		needs:
			"inbounder ballHandler | shooter | shooter | shooter | handoffBig rollMan",
		steps: [
			"5 move R_slot pop; 1 pass 5 inbound",
			"1 move R_wing jog",
			"5 handoff 1 get",
			"1 dribble high_post attack; 5 move rim roll",
		],
		options: [
			"1 three pull_up R_slot 2 5 - Handoff 3",
			"1 mid pull_up high_post 3 - - Handoff 2",
			"5 rim dunk rim 3 1 pocket Cut 2",
			"4 three catch_and_shoot R_corner 3 1 kickout Spotup 1",
			"3 three catch_and_shoot L_corner 3 1 skip Spotup 1",
		],
		risks: [
			"0 1 pass",
			"2 1 lost",
			"3 1 lost",
			"3 1 charge",
			"0 1 fiveSeconds",
		],
	},
	{
		id: "ato-screen-the-screener",
		cat: "half",
		use: 3,
		start: "R_wing* L_wing R_corner R_block L_elbow",
		needs:
			"passer | shooter screener offBallShooter | shooter | screener big | lobThreat big",
		steps: [
			"2 screen 5 L_elbow back; 5 move rim backdoor",
			"4 screen 2 L_lane down; 2 move top v_cut",
		],
		options: [
			"2 three catch_and_shoot top 1 1 swing OffScreen 4",
			"5 rim alley_oop rim 0 1 lob Cut 2",
			"4 rim layup rim 1 1 lob Cut 1 | 5 move R_dunker seal; 4 move rim slip",
			"3 three catch_and_shoot R_corner 1 1 kickout Spotup 1",
		],
		risks: ["0 2 screen", "1 4 screen"],
	},
	{
		id: "ato-guard-back-screen",
		cat: "half",
		use: 2,
		start: "R_slot* L_slot L_wing R_corner R_dunker",
		needs: "passer | shooter screener | cutter lobThreat | shooter | big",
		steps: ["2 screen 3 L_elbow back; 3 move rim backdoor", "2 move top pop"],
		options: [
			"2 three catch_and_shoot top 1 1 swing Spotup 4",
			"3 rim alley_oop rim 0 1 lob Cut 2",
			"5 rim dunk R_dunker 0 1 dump_off Cut 1",
			"4 three catch_and_shoot R_corner 1 1 kickout Spotup 1",
		],
		risks: ["0 2 screen"],
	},
	{
		id: "ato-iverson-flare",
		cat: "half",
		use: 2,
		start: "top* L_wing R_corner L_elbow R_elbow",
		needs:
			"ballHandler passer | shooter offBallShooter | shooter | screener | screener big",
		steps: [
			"4+5 screen 2 L_elbow+R_elbow iverson; 2 move R_slot iverson_cut",
			"1 dribble L_slot advance; 5 screen 2 R_slot flare; 2 move R_wing flare",
		],
		options: [
			"2 three catch_and_shoot R_wing 1 1 skip OffScreen 4",
			"5 rim layup rim 1 1 lob Cut 1 | 5 move rim slip",
			"2 three catch_and_shoot R_slot 0 1 chest OffScreen 1",
			"3 three catch_and_shoot R_corner 1 1 skip Spotup 1",
		],
		risks: ["1 5 screen"],
	},
	{
		id: "ato-inbounder-stagger",
		cat: "slob",
		use: 2,
		start: "L_wing inbound_sideline_R* R_block R_elbow top",
		needs:
			"shooter ballHandler | inbounder shooter offBallShooter | screener | screener big | passer big",
		steps: [
			"2 pass 5 inbound",
			"2 move R_dunker jog",
			"3+4 screen 2 R_block+R_elbow stagger; 2 move R_slot sprint",
		],
		options: [
			"2 three catch_and_shoot R_slot 2 5 swing OffScreen 4",
			"4 rim layup rim 2 5 bounce Cut 1 | 4 move rim slip",
			"1 three catch_and_shoot L_wing 2 5 swing Spotup 1",
		],
		risks: ["0 2 pass", "2 3 screen", "0 2 fiveSeconds"],
	},
	{
		id: "late-clock-high-pnr",
		cat: "late",
		use: 6,
		start: "top* R_corner L_corner L_wing R_elbow",
		needs:
			"ballHandler isoScorer | shooter | shooter | shooter | screener rollMan",
		steps: ["5 screen 1 top ball", "1 dribble R_slot attack; 5 move rim roll"],
		options: [
			"1 three step_back R_slot 1 - - PRBallHandler 3",
			"1 mid pull_up R_elbow 1 - - PRBallHandler 3 | 1 dribble R_elbow attack",
			"1 three pull_up top 0 - - PRBallHandler 2",
			"5 rim alley_oop rim 1 1 lob PRRollMan 1",
			"2 three catch_and_shoot R_corner 1 1 kickout Spotup 1",
		],
		risks: ["0 5 screen", "1 1 lost", "1 1 shotClock"],
	},
	{
		id: "late-clock-get-iso",
		cat: "late",
		use: 4,
		start: "R_wing L_wing L_corner R_corner top*",
		needs: "isoScorer | shooter | shooter | shooter | handoffBig",
		steps: [
			"5 dribble R_slot advance; 5 handoff 1 get",
			"5 move L_slot clear_out; 1 dribble R_elbow hesitation",
		],
		options: [
			"1 three pull_up R_slot 0 5 - Handoff 2",
			"1 mid fadeaway R_elbow 1 - - Isolation 3",
			"1 mid pull_up R_elbow 1 - - Isolation 2",
			"1 three step_back R_wing 1 - - Isolation 2 | 1 dribble R_wing step_back",
			"1 rim layup rim 1 - - Isolation 1 | 1 dribble rim attack",
		],
		risks: ["0 1 lost", "1 5 shotClock"],
	},
	{
		id: "two-for-one",
		cat: "late",
		use: 3,
		start: "backcourt_mid* R_hash backcourt_L backcourt_R own_L_outlet",
		needs:
			"ballHandler shooter | shooter | shooter | rimRunner | screener rollMan",
		steps: [
			"1 dribble L_hash advance; 2 move R_corner sprint; 3 move L_wing sprint; 4 move high_post sprint; 5 move backcourt_mid sprint",
			"1 dribble L_slot advance; 3 move L_corner sprint; 4 move rim sprint; 5 move top sprint",
			"5 screen 1 L_slot drag",
		],
		options: [
			"1 three pull_up L_slot 2 - - PRBallHandler 3",
			"2 three catch_and_shoot R_corner 1 1 skip Transition 2",
			"3 three catch_and_shoot L_corner 1 1 kickout Transition 1",
			"1 rim layup rim 2 - - PRBallHandler 2 | 4 move R_dunker seal; 1 dribble rim attack",
			"4 rim dunk rim 1 1 lob Transition 1",
		],
		risks: ["2 5 screen", "2 1 shotClock"],
	},
	{
		id: "last-shot-hold-iso",
		cat: "late",
		use: 3,
		start: "top* R_corner L_corner R_dunker L_dunker",
		needs: "isoScorer ballHandler | shooter | shooter | big | big rebounder",
		steps: ["1 dribble top hesitation", "1 dribble R_elbow crossover"],
		options: [
			"1 mid pull_up R_elbow 1 - - Isolation 3",
			"1 three step_back top 0 - - Isolation 2 | 1 dribble top step_back",
			"1 mid fadeaway R_elbow 1 - - Isolation 2",
			"1 rim layup rim 1 - - Isolation 2 | 1 dribble rim attack",
			"4 rim dunk R_dunker 1 1 dump_off Cut 1",
		],
		risks: ["1 1 lost", "1 1 shotClock"],
	},
	{
		id: "last-shot-three-stagger",
		cat: "slob",
		use: 2,
		start: "inbound_sideline_R* L_block R_block L_elbow R_elbow",
		needs:
			"inbounder passer | shooter offBallShooter | screener shooter | shooter ballHandler | screener big",
		steps: [
			"3+5 screen 2 R_block+R_elbow stagger; 2 move R_wing sprint; 4 move top pop",
		],
		options: [
			"2 three catch_and_shoot R_wing 0 1 inbound OffScreen 4",
			"4 three catch_and_shoot top 0 1 inbound Spotup 2",
			"3 three catch_and_shoot R_corner 0 1 inbound Spotup 1 | 3 move R_corner pop",
			"2 three step_back R_wing 0 - - OffScreen 1 | 1 pass 2 inbound",
		],
		risks: ["0 3 screen", "0 1 fiveSeconds"],
	},
	{
		id: "full-court-home-run",
		cat: "late",
		use: 1,
		start: "backcourt_L backcourt_R L_wing top inbound_own_baseline*",
		needs:
			"shooter | shooter | shooter | big postScorer | inbounder passer big",
		steps: [
			"4 move high_post flash; 3 move L_slot relocate; 1 move backcourt_mid sprint",
			"5 pass 4 overhead",
		],
		options: [
			"4 mid catch_and_shoot high_post 1 5 - Misc 2",
			"3 three catch_and_shoot L_slot 1 4 chest Misc 1",
			"1 three catch_and_shoot backcourt_mid 0 5 inbound Misc 3",
		],
		risks: ["1 5 pass", "1 5 shotClock"],
	},
	{
		id: "horns-chin",
		cat: "half",
		use: 3,
		start: "top* R_corner L_corner L_elbow R_elbow",
		needs:
			"cutter ballHandler | shooter | shooter | screener popBig | passer big",
		steps: [
			"1 pass 5 chest",
			"4 screen 1 high_post back; 1 move rim backdoor",
			"4 move L_slot pop",
		],
		options: [
			"1 rim layup rim 1 5 bounce Cut 3",
			"4 three catch_and_shoot L_slot 2 5 swing Spotup 2",
			"5 mid pull_up R_elbow 2 - - Isolation 1",
			"2 three catch_and_shoot R_corner 2 5 kickout Spotup 1",
		],
		risks: ["0 1 pass", "1 4 screen"],
	},
	{
		id: "blob-ram",
		cat: "blob",
		use: 3,
		start: "inbound_baseline_R* top R_corner L_elbow L_block",
		needs:
			"inbounder passer | cutter shooter | shooter | screener postScorer | screener popBig",
		steps: [
			"4 screen 5 L_lane down; 5 move high_post lift",
			"5 screen 2 high_post back; 2 move rim backdoor; 4 post L_block seal",
			"5 move top pop",
		],
		options: [
			"2 rim layup rim 1 1 lob Cut 3",
			"5 three catch_and_shoot top 2 1 inbound Spotup 2",
			"4 post hook L_block 1 1 inbound Postup 1",
			"3 three catch_and_shoot R_corner 1 1 inbound Spotup 1",
		],
		risks: ["0 4 screen", "1 5 screen", "0 1 fiveSeconds"],
	},
	{
		id: "slob-ram-pnr",
		cat: "slob",
		use: 2,
		start: "inbound_sideline_R* R_slot L_corner R_elbow R_block",
		needs:
			"inbounder shooter | ballHandler | shooter | screener shooter | screener rollMan",
		steps: [
			"2 move top v_cut; 1 pass 2 inbound",
			"4 screen 5 R_lane down; 5 move R_elbow sprint; 1 move R_wing jog",
			"5 screen 2 top ball; 4 move R_corner clear_out",
			"2 dribble L_elbow attack; 5 move rim roll",
		],
		options: [
			"5 rim dunk rim 3 2 pocket PRRollMan 3",
			"2 mid pull_up L_elbow 3 - - PRBallHandler 2",
			"3 three catch_and_shoot L_corner 3 2 kickout Spotup 1",
			"4 three catch_and_shoot R_corner 3 2 skip Spotup 1",
			"1 three catch_and_shoot R_wing 3 2 skip Spotup 1",
		],
		risks: [
			"0 1 pass",
			"1 4 screen",
			"2 5 screen",
			"3 2 lost",
			"0 1 fiveSeconds",
		],
	},
];
